"""Create inbox_entries table (CHT-1250).

Hand-trimmed from the `oxyde makemigrations` autogenerated diff: the raw
diff also proposed re-creating `ticket_limbo_blockers` and
`document_issues` (both already exist in real databases -- created via
raw SQL in migration 0005 and via an out-of-band model addition
respectively -- oxyde's schema-diff engine just doesn't have visibility
into tables it didn't itself CREATE) plus dropping/re-adding every
foreign key in the schema (an oxyde-version FK-naming artifact, not a
real schema change). None of that is part of this migration; it's
pre-existing drift for a separate cleanup. Only the new inbox_entries
table -- and its two lookup indexes -- belong here.

NOTE: another agent is using migration number 0009 for lease_expires_at
on a parallel branch. Expect this to be renumbered at merge time.

Created: 2026-07-06
"""

depends_on = "0008_unique_project_key_label_name"


def upgrade(ctx):
    """Apply migration."""
    ctx.create_table(
        "inbox_entries",
        fields=[
            {
                'name': 'id', 'python_type': 'str', 'db_type': None,
                'nullable': False, 'primary_key': True, 'unique': False,
                'default': None, 'auto_increment': False,
                'max_length': None, 'max_digits': None, 'decimal_places': None,
            },
            {
                'name': 'recipient_user_id', 'python_type': 'str', 'db_type': None,
                'nullable': False, 'primary_key': False, 'unique': False,
                'default': None, 'auto_increment': False,
                'max_length': None, 'max_digits': None, 'decimal_places': None,
            },
            {
                'name': 'kind', 'python_type': 'inboxentrykind', 'db_type': None,
                'nullable': False, 'primary_key': False, 'unique': False,
                'default': None, 'auto_increment': False,
                'max_length': None, 'max_digits': None, 'decimal_places': None,
            },
            {
                'name': 'team_id', 'python_type': 'str', 'db_type': None,
                'nullable': False, 'primary_key': False, 'unique': False,
                'default': None, 'auto_increment': False,
                'max_length': None, 'max_digits': None, 'decimal_places': None,
            },
            {
                'name': 'project_id', 'python_type': 'str', 'db_type': None,
                'nullable': True, 'primary_key': False, 'unique': False,
                'default': None, 'auto_increment': False,
                'max_length': None, 'max_digits': None, 'decimal_places': None,
            },
            {
                'name': 'issue_id', 'python_type': 'str', 'db_type': None,
                'nullable': True, 'primary_key': False, 'unique': False,
                'default': None, 'auto_increment': False,
                'max_length': None, 'max_digits': None, 'decimal_places': None,
            },
            {
                'name': 'document_id', 'python_type': 'str', 'db_type': None,
                'nullable': True, 'primary_key': False, 'unique': False,
                'default': None, 'auto_increment': False,
                'max_length': None, 'max_digits': None, 'decimal_places': None,
            },
            {
                'name': 'ritual_id', 'python_type': 'str', 'db_type': None,
                'nullable': True, 'primary_key': False, 'unique': False,
                'default': None, 'auto_increment': False,
                'max_length': None, 'max_digits': None, 'decimal_places': None,
            },
            {
                'name': 'source_user_id', 'python_type': 'str', 'db_type': None,
                'nullable': True, 'primary_key': False, 'unique': False,
                'default': None, 'auto_increment': False,
                'max_length': None, 'max_digits': None, 'decimal_places': None,
            },
            {
                'name': 'title', 'python_type': 'str', 'db_type': None,
                'nullable': False, 'primary_key': False, 'unique': False,
                'default': None, 'auto_increment': False,
                'max_length': None, 'max_digits': None, 'decimal_places': None,
            },
            {
                'name': 'body', 'python_type': 'str', 'db_type': None,
                'nullable': True, 'primary_key': False, 'unique': False,
                'default': None, 'auto_increment': False,
                'max_length': None, 'max_digits': None, 'decimal_places': None,
            },
            {
                'name': 'created_at', 'python_type': 'datetime', 'db_type': None,
                'nullable': False, 'primary_key': False, 'unique': False,
                'default': None, 'auto_increment': False,
                'max_length': None, 'max_digits': None, 'decimal_places': None,
            },
            {
                'name': 'read_at', 'python_type': 'datetime', 'db_type': None,
                'nullable': True, 'primary_key': False, 'unique': False,
                'default': None, 'auto_increment': False,
                'max_length': None, 'max_digits': None, 'decimal_places': None,
            },
        ],
    )
    # Every list/unread-count query filters by one of these; non-unique,
    # hand-added (oxyde's makemigrations diff doesn't emit create_index for
    # plain db_index=True fields -- same reasoning as 0008's compound
    # unique indexes, just non-unique here).
    ctx.create_index("inbox_entries", {
        "name": "inbox_entries_recipient_user_id_idx",
        "fields": ["recipient_user_id"],
        "unique": False,
        "method": None,
        "where": None,
    })
    ctx.create_index("inbox_entries", {
        "name": "inbox_entries_team_id_idx",
        "fields": ["team_id"],
        "unique": False,
        "method": None,
        "where": None,
    })


def downgrade(ctx):
    """Revert migration."""
    ctx.drop_index("inbox_entries", "inbox_entries_team_id_idx")
    ctx.drop_index("inbox_entries", "inbox_entries_recipient_user_id_idx")
    ctx.drop_table("inbox_entries")
