"""Rituals declare an artifact; attestations record the verified one (CHT-1359).

`rituals.artifact` (DbEnum RitualArtifact: document | url, NULL for none)
says what an attestation must point at, and `ritual_attestations.
artifact_ref` stores the document id or URL the service verified at
attest time. Both nullable, so existing rows need nothing.

Generated by `oxyde makemigrations --name ritual_artifact` -- the first
migration the tool has produced since 0004, because 0017 brought the
replay back in line with the models (CHT-1410).

Created: 2026-09-06 14:01:40
"""

depends_on = "0017_record_hand_written_schema_state"


def upgrade(ctx):
    """Apply migration."""
    ctx.add_column("ritual_attestations", {
    'name': 'artifact_ref',
    'python_type': 'str',
    'db_type': None,
    'nullable': True,
    'primary_key': False,
    'unique': False,
    'default': None,
    'auto_increment': False,
    'max_length': None,
    'max_digits': None,
    'decimal_places': None
})
    ctx.add_column("rituals", {
    'name': 'artifact',
    'python_type': 'ritualartifact',
    'db_type': None,
    'nullable': True,
    'primary_key': False,
    'unique': False,
    'default': None,
    'auto_increment': False,
    'max_length': None,
    'max_digits': None,
    'decimal_places': None
})


def downgrade(ctx):
    """Revert migration."""
    ctx.drop_column("rituals", "artifact")
    ctx.drop_column("ritual_attestations", "artifact_ref")
