# Auto-generated by oxyde generate-stubs
# DO NOT EDIT - This file will be overwritten

from typing import Any, ClassVar, Literal
from datetime import datetime, date, time
from decimal import Decimal
from uuid import UUID

from oxyde import Model
from oxyde.queries import Query, QueryManager

import uuid
from datetime import datetime, timezone
from app.utils.datetimes import DateTimeUTC
from oxyde import Model, Field
from app.enums import InboxEntryKind
from app.oxyde_models.enums import DbEnum

class OxydeInboxEntry(Model):
    class Meta:
        is_table: bool
        table_name: str
    id: str
    recipient_user_id: str
    kind: InboxEntryKind
    team_id: str
    project_id: str | None
    issue_id: str | None
    document_id: str | None
    ritual_id: str | None
    source_user_id: str | None
    title: str
    body: str | None
    created_at: datetime
    read_at: Annotated[datetime.datetime, BeforeValidator(func=<function ensure_utc at 0x108bd56c0>, json_schema_input_type=PydanticUndefined)] | None
    objects: ClassVar["OxydeInboxEntryManager"]


class OxydeInboxEntryQuery(Query[OxydeInboxEntry]):
    """Type-safe Query for OxydeInboxEntry model."""

    # Query building methods (sync, return Query)

    def filter(
        self,
        *args: Any,
        body: str | None = None,
        body__contains: str | None = None,
        body__icontains: str | None = None,
        body__startswith: str | None = None,
        body__istartswith: str | None = None,
        body__endswith: str | None = None,
        body__iendswith: str | None = None,
        body__iexact: str | None = None,
        body__in: list[str] | None = None,
        body__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        document_id: str | None = None,
        document_id__contains: str | None = None,
        document_id__icontains: str | None = None,
        document_id__startswith: str | None = None,
        document_id__istartswith: str | None = None,
        document_id__endswith: str | None = None,
        document_id__iendswith: str | None = None,
        document_id__iexact: str | None = None,
        document_id__in: list[str] | None = None,
        document_id__isnull: bool | None = None,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        issue_id: str | None = None,
        issue_id__contains: str | None = None,
        issue_id__icontains: str | None = None,
        issue_id__startswith: str | None = None,
        issue_id__istartswith: str | None = None,
        issue_id__endswith: str | None = None,
        issue_id__iendswith: str | None = None,
        issue_id__iexact: str | None = None,
        issue_id__in: list[str] | None = None,
        issue_id__isnull: bool | None = None,
        kind: InboxEntryKind | None = None,
        kind__in: list[InboxEntryKind] | None = None,
        kind__isnull: bool | None = None,
        project_id: str | None = None,
        project_id__contains: str | None = None,
        project_id__icontains: str | None = None,
        project_id__startswith: str | None = None,
        project_id__istartswith: str | None = None,
        project_id__endswith: str | None = None,
        project_id__iendswith: str | None = None,
        project_id__iexact: str | None = None,
        project_id__in: list[str] | None = None,
        project_id__isnull: bool | None = None,
        read_at: Annotated[datetime.datetime, BeforeValidator(func=<function ensure_utc at 0x108bd56c0>, json_schema_input_type=PydanticUndefined)] | None = None,
        read_at__in: list[Annotated[datetime.datetime, BeforeValidator(func=<function ensure_utc at 0x108bd56c0>, json_schema_input_type=PydanticUndefined)]] | None = None,
        read_at__isnull: bool | None = None,
        recipient_user_id: str | None = None,
        recipient_user_id__contains: str | None = None,
        recipient_user_id__icontains: str | None = None,
        recipient_user_id__startswith: str | None = None,
        recipient_user_id__istartswith: str | None = None,
        recipient_user_id__endswith: str | None = None,
        recipient_user_id__iendswith: str | None = None,
        recipient_user_id__iexact: str | None = None,
        recipient_user_id__in: list[str] | None = None,
        recipient_user_id__isnull: bool | None = None,
        ritual_id: str | None = None,
        ritual_id__contains: str | None = None,
        ritual_id__icontains: str | None = None,
        ritual_id__startswith: str | None = None,
        ritual_id__istartswith: str | None = None,
        ritual_id__endswith: str | None = None,
        ritual_id__iendswith: str | None = None,
        ritual_id__iexact: str | None = None,
        ritual_id__in: list[str] | None = None,
        ritual_id__isnull: bool | None = None,
        source_user_id: str | None = None,
        source_user_id__contains: str | None = None,
        source_user_id__icontains: str | None = None,
        source_user_id__startswith: str | None = None,
        source_user_id__istartswith: str | None = None,
        source_user_id__endswith: str | None = None,
        source_user_id__iendswith: str | None = None,
        source_user_id__iexact: str | None = None,
        source_user_id__in: list[str] | None = None,
        source_user_id__isnull: bool | None = None,
        team_id: str | None = None,
        team_id__contains: str | None = None,
        team_id__icontains: str | None = None,
        team_id__startswith: str | None = None,
        team_id__istartswith: str | None = None,
        team_id__endswith: str | None = None,
        team_id__iendswith: str | None = None,
        team_id__iexact: str | None = None,
        team_id__in: list[str] | None = None,
        team_id__isnull: bool | None = None,
        title: str | None = None,
        title__contains: str | None = None,
        title__icontains: str | None = None,
        title__startswith: str | None = None,
        title__istartswith: str | None = None,
        title__endswith: str | None = None,
        title__iendswith: str | None = None,
        title__iexact: str | None = None,
        title__in: list[str] | None = None,
        title__isnull: bool | None = None,
    ) -> "OxydeInboxEntryQuery":
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        body: str | None = None,
        body__contains: str | None = None,
        body__icontains: str | None = None,
        body__startswith: str | None = None,
        body__istartswith: str | None = None,
        body__endswith: str | None = None,
        body__iendswith: str | None = None,
        body__iexact: str | None = None,
        body__in: list[str] | None = None,
        body__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        document_id: str | None = None,
        document_id__contains: str | None = None,
        document_id__icontains: str | None = None,
        document_id__startswith: str | None = None,
        document_id__istartswith: str | None = None,
        document_id__endswith: str | None = None,
        document_id__iendswith: str | None = None,
        document_id__iexact: str | None = None,
        document_id__in: list[str] | None = None,
        document_id__isnull: bool | None = None,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        issue_id: str | None = None,
        issue_id__contains: str | None = None,
        issue_id__icontains: str | None = None,
        issue_id__startswith: str | None = None,
        issue_id__istartswith: str | None = None,
        issue_id__endswith: str | None = None,
        issue_id__iendswith: str | None = None,
        issue_id__iexact: str | None = None,
        issue_id__in: list[str] | None = None,
        issue_id__isnull: bool | None = None,
        kind: InboxEntryKind | None = None,
        kind__in: list[InboxEntryKind] | None = None,
        kind__isnull: bool | None = None,
        project_id: str | None = None,
        project_id__contains: str | None = None,
        project_id__icontains: str | None = None,
        project_id__startswith: str | None = None,
        project_id__istartswith: str | None = None,
        project_id__endswith: str | None = None,
        project_id__iendswith: str | None = None,
        project_id__iexact: str | None = None,
        project_id__in: list[str] | None = None,
        project_id__isnull: bool | None = None,
        read_at: Annotated[datetime.datetime, BeforeValidator(func=<function ensure_utc at 0x108bd56c0>, json_schema_input_type=PydanticUndefined)] | None = None,
        read_at__in: list[Annotated[datetime.datetime, BeforeValidator(func=<function ensure_utc at 0x108bd56c0>, json_schema_input_type=PydanticUndefined)]] | None = None,
        read_at__isnull: bool | None = None,
        recipient_user_id: str | None = None,
        recipient_user_id__contains: str | None = None,
        recipient_user_id__icontains: str | None = None,
        recipient_user_id__startswith: str | None = None,
        recipient_user_id__istartswith: str | None = None,
        recipient_user_id__endswith: str | None = None,
        recipient_user_id__iendswith: str | None = None,
        recipient_user_id__iexact: str | None = None,
        recipient_user_id__in: list[str] | None = None,
        recipient_user_id__isnull: bool | None = None,
        ritual_id: str | None = None,
        ritual_id__contains: str | None = None,
        ritual_id__icontains: str | None = None,
        ritual_id__startswith: str | None = None,
        ritual_id__istartswith: str | None = None,
        ritual_id__endswith: str | None = None,
        ritual_id__iendswith: str | None = None,
        ritual_id__iexact: str | None = None,
        ritual_id__in: list[str] | None = None,
        ritual_id__isnull: bool | None = None,
        source_user_id: str | None = None,
        source_user_id__contains: str | None = None,
        source_user_id__icontains: str | None = None,
        source_user_id__startswith: str | None = None,
        source_user_id__istartswith: str | None = None,
        source_user_id__endswith: str | None = None,
        source_user_id__iendswith: str | None = None,
        source_user_id__iexact: str | None = None,
        source_user_id__in: list[str] | None = None,
        source_user_id__isnull: bool | None = None,
        team_id: str | None = None,
        team_id__contains: str | None = None,
        team_id__icontains: str | None = None,
        team_id__startswith: str | None = None,
        team_id__istartswith: str | None = None,
        team_id__endswith: str | None = None,
        team_id__iendswith: str | None = None,
        team_id__iexact: str | None = None,
        team_id__in: list[str] | None = None,
        team_id__isnull: bool | None = None,
        title: str | None = None,
        title__contains: str | None = None,
        title__icontains: str | None = None,
        title__startswith: str | None = None,
        title__istartswith: str | None = None,
        title__endswith: str | None = None,
        title__iendswith: str | None = None,
        title__iexact: str | None = None,
        title__in: list[str] | None = None,
        title__isnull: bool | None = None,
    ) -> "OxydeInboxEntryQuery":
        """Exclude objects matching field lookups."""
        ...

    def order_by(self, *fields: Literal["body", "-body", "created_at", "-created_at", "document_id", "-document_id", "id", "-id", "issue_id", "-issue_id", "kind", "-kind", "project_id", "-project_id", "read_at", "-read_at", "recipient_user_id", "-recipient_user_id", "ritual_id", "-ritual_id", "source_user_id", "-source_user_id", "team_id", "-team_id", "title", "-title"]) -> "OxydeInboxEntryQuery":  # type: ignore[override]
        """Order results by fields."""
        ...

    def limit(self, n: int) -> "OxydeInboxEntryQuery":
        """Limit number of results."""
        ...

    def offset(self, n: int) -> "OxydeInboxEntryQuery":
        """Skip first n results."""
        ...

    def distinct(self, value: bool = True) -> "OxydeInboxEntryQuery":
        """Return distinct results."""
        ...

    def select(self, *fields: Literal["body", "created_at", "document_id", "id", "issue_id", "kind", "project_id", "read_at", "recipient_user_id", "ritual_id", "source_user_id", "team_id", "title"]) -> "OxydeInboxEntryQuery":  # type: ignore[override]
        """Select specific fields."""
        ...

    def join(self, *paths: str) -> "OxydeInboxEntryQuery":
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> "OxydeInboxEntryQuery":
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> "OxydeInboxEntryQuery":
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> "OxydeInboxEntryQuery":
        """Add FOR SHARE lock to query."""
        ...

    def annotate(self, **annotations: Any) -> "OxydeInboxEntryQuery":
        """Add computed fields using aggregate functions."""
        ...

    def group_by(self, *fields: Literal["body", "created_at", "document_id", "id", "issue_id", "kind", "project_id", "read_at", "recipient_user_id", "ritual_id", "source_user_id", "team_id", "title"]) -> "OxydeInboxEntryQuery":  # type: ignore[override]
        """Add GROUP BY clause."""
        ...

    def having(self, *q_exprs: Any, **kwargs: Any) -> "OxydeInboxEntryQuery":
        """Add HAVING clause for filtering grouped results."""
        ...

    def values(self, *fields: Literal["body", "created_at", "document_id", "id", "issue_id", "kind", "project_id", "read_at", "recipient_user_id", "ritual_id", "source_user_id", "team_id", "title"]) -> "OxydeInboxEntryQuery":  # type: ignore[override]
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["body", "created_at", "document_id", "id", "issue_id", "kind", "project_id", "read_at", "recipient_user_id", "ritual_id", "source_user_id", "team_id", "title"], flat: bool = False) -> "OxydeInboxEntryQuery":  # type: ignore[override]
        """Return tuples/values instead of models."""
        ...

    # Terminal methods (async, execute query)

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[OxydeInboxEntry]:
        """Execute query and return all results."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> OxydeInboxEntry | None:
        """Execute query and return first result."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> OxydeInboxEntry | None:
        """Execute query and return last result."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count matching objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def update(  # type: ignore[override]
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **values: Any,
    ) -> int:
        """Update matching objects."""
        ...

    async def increment(
        self,
        field: str,
        by: int | float = 1,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Atomically increment a field value."""
        ...

    async def delete(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Delete matching objects."""
        ...

class OxydeInboxEntryManager(QueryManager[OxydeInboxEntry]):
    """Type-safe Manager for OxydeInboxEntry model."""

    # Query building methods (sync, return Query)

    def query(self) -> OxydeInboxEntryQuery:
        """Return a Query builder for this model."""
        ...

    def filter(
        self,
        *args: Any,
        body: str | None = None,
        body__contains: str | None = None,
        body__icontains: str | None = None,
        body__startswith: str | None = None,
        body__istartswith: str | None = None,
        body__endswith: str | None = None,
        body__iendswith: str | None = None,
        body__iexact: str | None = None,
        body__in: list[str] | None = None,
        body__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        document_id: str | None = None,
        document_id__contains: str | None = None,
        document_id__icontains: str | None = None,
        document_id__startswith: str | None = None,
        document_id__istartswith: str | None = None,
        document_id__endswith: str | None = None,
        document_id__iendswith: str | None = None,
        document_id__iexact: str | None = None,
        document_id__in: list[str] | None = None,
        document_id__isnull: bool | None = None,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        issue_id: str | None = None,
        issue_id__contains: str | None = None,
        issue_id__icontains: str | None = None,
        issue_id__startswith: str | None = None,
        issue_id__istartswith: str | None = None,
        issue_id__endswith: str | None = None,
        issue_id__iendswith: str | None = None,
        issue_id__iexact: str | None = None,
        issue_id__in: list[str] | None = None,
        issue_id__isnull: bool | None = None,
        kind: InboxEntryKind | None = None,
        kind__in: list[InboxEntryKind] | None = None,
        kind__isnull: bool | None = None,
        project_id: str | None = None,
        project_id__contains: str | None = None,
        project_id__icontains: str | None = None,
        project_id__startswith: str | None = None,
        project_id__istartswith: str | None = None,
        project_id__endswith: str | None = None,
        project_id__iendswith: str | None = None,
        project_id__iexact: str | None = None,
        project_id__in: list[str] | None = None,
        project_id__isnull: bool | None = None,
        read_at: Annotated[datetime.datetime, BeforeValidator(func=<function ensure_utc at 0x108bd56c0>, json_schema_input_type=PydanticUndefined)] | None = None,
        read_at__in: list[Annotated[datetime.datetime, BeforeValidator(func=<function ensure_utc at 0x108bd56c0>, json_schema_input_type=PydanticUndefined)]] | None = None,
        read_at__isnull: bool | None = None,
        recipient_user_id: str | None = None,
        recipient_user_id__contains: str | None = None,
        recipient_user_id__icontains: str | None = None,
        recipient_user_id__startswith: str | None = None,
        recipient_user_id__istartswith: str | None = None,
        recipient_user_id__endswith: str | None = None,
        recipient_user_id__iendswith: str | None = None,
        recipient_user_id__iexact: str | None = None,
        recipient_user_id__in: list[str] | None = None,
        recipient_user_id__isnull: bool | None = None,
        ritual_id: str | None = None,
        ritual_id__contains: str | None = None,
        ritual_id__icontains: str | None = None,
        ritual_id__startswith: str | None = None,
        ritual_id__istartswith: str | None = None,
        ritual_id__endswith: str | None = None,
        ritual_id__iendswith: str | None = None,
        ritual_id__iexact: str | None = None,
        ritual_id__in: list[str] | None = None,
        ritual_id__isnull: bool | None = None,
        source_user_id: str | None = None,
        source_user_id__contains: str | None = None,
        source_user_id__icontains: str | None = None,
        source_user_id__startswith: str | None = None,
        source_user_id__istartswith: str | None = None,
        source_user_id__endswith: str | None = None,
        source_user_id__iendswith: str | None = None,
        source_user_id__iexact: str | None = None,
        source_user_id__in: list[str] | None = None,
        source_user_id__isnull: bool | None = None,
        team_id: str | None = None,
        team_id__contains: str | None = None,
        team_id__icontains: str | None = None,
        team_id__startswith: str | None = None,
        team_id__istartswith: str | None = None,
        team_id__endswith: str | None = None,
        team_id__iendswith: str | None = None,
        team_id__iexact: str | None = None,
        team_id__in: list[str] | None = None,
        team_id__isnull: bool | None = None,
        title: str | None = None,
        title__contains: str | None = None,
        title__icontains: str | None = None,
        title__startswith: str | None = None,
        title__istartswith: str | None = None,
        title__endswith: str | None = None,
        title__iendswith: str | None = None,
        title__iexact: str | None = None,
        title__in: list[str] | None = None,
        title__isnull: bool | None = None,
    ) -> OxydeInboxEntryQuery:
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        body: str | None = None,
        body__contains: str | None = None,
        body__icontains: str | None = None,
        body__startswith: str | None = None,
        body__istartswith: str | None = None,
        body__endswith: str | None = None,
        body__iendswith: str | None = None,
        body__iexact: str | None = None,
        body__in: list[str] | None = None,
        body__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        document_id: str | None = None,
        document_id__contains: str | None = None,
        document_id__icontains: str | None = None,
        document_id__startswith: str | None = None,
        document_id__istartswith: str | None = None,
        document_id__endswith: str | None = None,
        document_id__iendswith: str | None = None,
        document_id__iexact: str | None = None,
        document_id__in: list[str] | None = None,
        document_id__isnull: bool | None = None,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        issue_id: str | None = None,
        issue_id__contains: str | None = None,
        issue_id__icontains: str | None = None,
        issue_id__startswith: str | None = None,
        issue_id__istartswith: str | None = None,
        issue_id__endswith: str | None = None,
        issue_id__iendswith: str | None = None,
        issue_id__iexact: str | None = None,
        issue_id__in: list[str] | None = None,
        issue_id__isnull: bool | None = None,
        kind: InboxEntryKind | None = None,
        kind__in: list[InboxEntryKind] | None = None,
        kind__isnull: bool | None = None,
        project_id: str | None = None,
        project_id__contains: str | None = None,
        project_id__icontains: str | None = None,
        project_id__startswith: str | None = None,
        project_id__istartswith: str | None = None,
        project_id__endswith: str | None = None,
        project_id__iendswith: str | None = None,
        project_id__iexact: str | None = None,
        project_id__in: list[str] | None = None,
        project_id__isnull: bool | None = None,
        read_at: Annotated[datetime.datetime, BeforeValidator(func=<function ensure_utc at 0x108bd56c0>, json_schema_input_type=PydanticUndefined)] | None = None,
        read_at__in: list[Annotated[datetime.datetime, BeforeValidator(func=<function ensure_utc at 0x108bd56c0>, json_schema_input_type=PydanticUndefined)]] | None = None,
        read_at__isnull: bool | None = None,
        recipient_user_id: str | None = None,
        recipient_user_id__contains: str | None = None,
        recipient_user_id__icontains: str | None = None,
        recipient_user_id__startswith: str | None = None,
        recipient_user_id__istartswith: str | None = None,
        recipient_user_id__endswith: str | None = None,
        recipient_user_id__iendswith: str | None = None,
        recipient_user_id__iexact: str | None = None,
        recipient_user_id__in: list[str] | None = None,
        recipient_user_id__isnull: bool | None = None,
        ritual_id: str | None = None,
        ritual_id__contains: str | None = None,
        ritual_id__icontains: str | None = None,
        ritual_id__startswith: str | None = None,
        ritual_id__istartswith: str | None = None,
        ritual_id__endswith: str | None = None,
        ritual_id__iendswith: str | None = None,
        ritual_id__iexact: str | None = None,
        ritual_id__in: list[str] | None = None,
        ritual_id__isnull: bool | None = None,
        source_user_id: str | None = None,
        source_user_id__contains: str | None = None,
        source_user_id__icontains: str | None = None,
        source_user_id__startswith: str | None = None,
        source_user_id__istartswith: str | None = None,
        source_user_id__endswith: str | None = None,
        source_user_id__iendswith: str | None = None,
        source_user_id__iexact: str | None = None,
        source_user_id__in: list[str] | None = None,
        source_user_id__isnull: bool | None = None,
        team_id: str | None = None,
        team_id__contains: str | None = None,
        team_id__icontains: str | None = None,
        team_id__startswith: str | None = None,
        team_id__istartswith: str | None = None,
        team_id__endswith: str | None = None,
        team_id__iendswith: str | None = None,
        team_id__iexact: str | None = None,
        team_id__in: list[str] | None = None,
        team_id__isnull: bool | None = None,
        title: str | None = None,
        title__contains: str | None = None,
        title__icontains: str | None = None,
        title__startswith: str | None = None,
        title__istartswith: str | None = None,
        title__endswith: str | None = None,
        title__iendswith: str | None = None,
        title__iexact: str | None = None,
        title__in: list[str] | None = None,
        title__isnull: bool | None = None,
    ) -> OxydeInboxEntryQuery:
        """Exclude objects matching field lookups."""
        ...

    def values(self, *fields: Literal["body", "created_at", "document_id", "id", "issue_id", "kind", "project_id", "read_at", "recipient_user_id", "ritual_id", "source_user_id", "team_id", "title"]) -> OxydeInboxEntryQuery:  # type: ignore[override]
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["body", "created_at", "document_id", "id", "issue_id", "kind", "project_id", "read_at", "recipient_user_id", "ritual_id", "source_user_id", "team_id", "title"], flat: bool = False) -> OxydeInboxEntryQuery:  # type: ignore[override]
        """Return tuples/values instead of models."""
        ...

    def distinct(self, distinct: bool = True) -> OxydeInboxEntryQuery:
        """Return distinct results."""
        ...

    def join(self, *paths: str) -> OxydeInboxEntryQuery:
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> OxydeInboxEntryQuery:
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> OxydeInboxEntryQuery:
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> OxydeInboxEntryQuery:
        """Add FOR SHARE lock to query."""
        ...

    # Terminal methods (async, execute query)

    async def get(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> OxydeInboxEntry:
        """Get single object matching lookups."""
        ...

    async def get_or_none(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> OxydeInboxEntry | None:
        """Get object or None if not found."""
        ...

    async def get_or_create(
        self,
        *,
        defaults: dict[str, Any] | None = None,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> tuple[OxydeInboxEntry, bool]:
        """Get object or create if not found. Returns (object, created)."""
        ...

    async def update_or_create(
        self,
        *,
        defaults: dict[str, Any] | None = None,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> tuple[OxydeInboxEntry, bool]:
        """Get object, create if missing, or update it when defaults are provided."""
        ...

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        mode: str = "models",
    ) -> list[OxydeInboxEntry]:
        """Get all objects."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> OxydeInboxEntry | None:
        """Get first object."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> OxydeInboxEntry | None:
        """Get last object."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count all objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def create(  # type: ignore[override]
        self,
        *,
        instance: OxydeInboxEntry | None = None,
        client: Any | None = None,
        using: str | None = None,
        body: str | None = None,
        created_at: datetime | None = None,
        document_id: str | None = None,
        id: str | None = None,
        issue_id: str | None = None,
        kind: InboxEntryKind | None = None,
        project_id: str | None = None,
        read_at: Annotated[datetime.datetime, BeforeValidator(func=<function ensure_utc at 0x108bd56c0>, json_schema_input_type=PydanticUndefined)] | None = None,
        recipient_user_id: str | None = None,
        ritual_id: str | None = None,
        source_user_id: str | None = None,
        team_id: str | None = None,
        title: str | None = None,
    ) -> OxydeInboxEntry:
        """Create new object."""
        ...

    async def bulk_create(  # type: ignore[override]
        self,
        objects: list[OxydeInboxEntry],
        *,
        batch_size: int | None = None,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[OxydeInboxEntry]:
        """Bulk create objects."""
        ...

    async def bulk_update(  # type: ignore[override]
        self,
        objects: list[OxydeInboxEntry],
        fields: list[str],
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Bulk update objects."""
        ...

