# Auto-generated by oxyde generate-stubs
# DO NOT EDIT - This file will be overwritten

from typing import Any, Literal
from datetime import datetime, date, time
from decimal import Decimal
from uuid import UUID

from oxyde import OxydeModel
from oxyde.queries import Query, QueryManager


class OxydeProject(OxydeModel):
    class Meta:
        is_table: bool
        table_name: str
    id: str
    team_id: str
    name: str
    key: str
    description: str | None
    color: str
    icon: str | None
    lead_id: str | None
    issue_count: int
    estimate_scale: <enum 'EstimateScale'>
    unestimated_handling: <enum 'UnestimatedHandling'>
    default_sprint_budget: int | None
    human_rituals_required: bool
    require_estimate_on_claim: bool
    created_at: datetime
    updated_at: datetime
    objects: "OxydeProjectManager"


class OxydeProjectQuery(Query[OxydeProject]):
    """Type-safe Query for OxydeProject model."""

    # Query building methods (sync, return Query)

    def filter(
        self,
        *args: Any,
        color: str | None = None,
        color__contains: str | None = None,
        color__icontains: str | None = None,
        color__startswith: str | None = None,
        color__istartswith: str | None = None,
        color__endswith: str | None = None,
        color__iendswith: str | None = None,
        color__iexact: str | None = None,
        color__in: list[str] | None = None,
        color__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        default_sprint_budget: int | None = None,
        default_sprint_budget__gt: int | None = None,
        default_sprint_budget__gte: int | None = None,
        default_sprint_budget__lt: int | None = None,
        default_sprint_budget__lte: int | None = None,
        default_sprint_budget__between: tuple[int, int] | None = None,
        default_sprint_budget__range: int | None = None,
        default_sprint_budget__in: list[int] | None = None,
        default_sprint_budget__isnull: bool | None = None,
        description: str | None = None,
        description__contains: str | None = None,
        description__icontains: str | None = None,
        description__startswith: str | None = None,
        description__istartswith: str | None = None,
        description__endswith: str | None = None,
        description__iendswith: str | None = None,
        description__iexact: str | None = None,
        description__in: list[str] | None = None,
        description__isnull: bool | None = None,
        estimate_scale: <enum 'EstimateScale'> | None = None,
        estimate_scale__in: list[<enum 'EstimateScale'>] | None = None,
        estimate_scale__isnull: bool | None = None,
        human_rituals_required: bool | None = None,
        human_rituals_required__in: list[bool] | None = None,
        human_rituals_required__isnull: bool | None = None,
        icon: str | None = None,
        icon__contains: str | None = None,
        icon__icontains: str | None = None,
        icon__startswith: str | None = None,
        icon__istartswith: str | None = None,
        icon__endswith: str | None = None,
        icon__iendswith: str | None = None,
        icon__iexact: str | None = None,
        icon__in: list[str] | None = None,
        icon__isnull: bool | None = None,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        issue_count: int | None = None,
        issue_count__gt: int | None = None,
        issue_count__gte: int | None = None,
        issue_count__lt: int | None = None,
        issue_count__lte: int | None = None,
        issue_count__between: tuple[int, int] | None = None,
        issue_count__range: int | None = None,
        issue_count__in: list[int] | None = None,
        issue_count__isnull: bool | None = None,
        key: str | None = None,
        key__contains: str | None = None,
        key__icontains: str | None = None,
        key__startswith: str | None = None,
        key__istartswith: str | None = None,
        key__endswith: str | None = None,
        key__iendswith: str | None = None,
        key__iexact: str | None = None,
        key__in: list[str] | None = None,
        key__isnull: bool | None = None,
        lead_id: str | None = None,
        lead_id__contains: str | None = None,
        lead_id__icontains: str | None = None,
        lead_id__startswith: str | None = None,
        lead_id__istartswith: str | None = None,
        lead_id__endswith: str | None = None,
        lead_id__iendswith: str | None = None,
        lead_id__iexact: str | None = None,
        lead_id__in: list[str] | None = None,
        lead_id__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        require_estimate_on_claim: bool | None = None,
        require_estimate_on_claim__in: list[bool] | None = None,
        require_estimate_on_claim__isnull: bool | None = None,
        team_id: str | None = None,
        team_id__contains: str | None = None,
        team_id__icontains: str | None = None,
        team_id__startswith: str | None = None,
        team_id__istartswith: str | None = None,
        team_id__endswith: str | None = None,
        team_id__iendswith: str | None = None,
        team_id__iexact: str | None = None,
        team_id__in: list[str] | None = None,
        team_id__isnull: bool | None = None,
        unestimated_handling: <enum 'UnestimatedHandling'> | None = None,
        unestimated_handling__in: list[<enum 'UnestimatedHandling'>] | None = None,
        unestimated_handling__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
    ) -> "OxydeProjectQuery":
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        color: str | None = None,
        color__contains: str | None = None,
        color__icontains: str | None = None,
        color__startswith: str | None = None,
        color__istartswith: str | None = None,
        color__endswith: str | None = None,
        color__iendswith: str | None = None,
        color__iexact: str | None = None,
        color__in: list[str] | None = None,
        color__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        default_sprint_budget: int | None = None,
        default_sprint_budget__gt: int | None = None,
        default_sprint_budget__gte: int | None = None,
        default_sprint_budget__lt: int | None = None,
        default_sprint_budget__lte: int | None = None,
        default_sprint_budget__between: tuple[int, int] | None = None,
        default_sprint_budget__range: int | None = None,
        default_sprint_budget__in: list[int] | None = None,
        default_sprint_budget__isnull: bool | None = None,
        description: str | None = None,
        description__contains: str | None = None,
        description__icontains: str | None = None,
        description__startswith: str | None = None,
        description__istartswith: str | None = None,
        description__endswith: str | None = None,
        description__iendswith: str | None = None,
        description__iexact: str | None = None,
        description__in: list[str] | None = None,
        description__isnull: bool | None = None,
        estimate_scale: <enum 'EstimateScale'> | None = None,
        estimate_scale__in: list[<enum 'EstimateScale'>] | None = None,
        estimate_scale__isnull: bool | None = None,
        human_rituals_required: bool | None = None,
        human_rituals_required__in: list[bool] | None = None,
        human_rituals_required__isnull: bool | None = None,
        icon: str | None = None,
        icon__contains: str | None = None,
        icon__icontains: str | None = None,
        icon__startswith: str | None = None,
        icon__istartswith: str | None = None,
        icon__endswith: str | None = None,
        icon__iendswith: str | None = None,
        icon__iexact: str | None = None,
        icon__in: list[str] | None = None,
        icon__isnull: bool | None = None,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        issue_count: int | None = None,
        issue_count__gt: int | None = None,
        issue_count__gte: int | None = None,
        issue_count__lt: int | None = None,
        issue_count__lte: int | None = None,
        issue_count__between: tuple[int, int] | None = None,
        issue_count__range: int | None = None,
        issue_count__in: list[int] | None = None,
        issue_count__isnull: bool | None = None,
        key: str | None = None,
        key__contains: str | None = None,
        key__icontains: str | None = None,
        key__startswith: str | None = None,
        key__istartswith: str | None = None,
        key__endswith: str | None = None,
        key__iendswith: str | None = None,
        key__iexact: str | None = None,
        key__in: list[str] | None = None,
        key__isnull: bool | None = None,
        lead_id: str | None = None,
        lead_id__contains: str | None = None,
        lead_id__icontains: str | None = None,
        lead_id__startswith: str | None = None,
        lead_id__istartswith: str | None = None,
        lead_id__endswith: str | None = None,
        lead_id__iendswith: str | None = None,
        lead_id__iexact: str | None = None,
        lead_id__in: list[str] | None = None,
        lead_id__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        require_estimate_on_claim: bool | None = None,
        require_estimate_on_claim__in: list[bool] | None = None,
        require_estimate_on_claim__isnull: bool | None = None,
        team_id: str | None = None,
        team_id__contains: str | None = None,
        team_id__icontains: str | None = None,
        team_id__startswith: str | None = None,
        team_id__istartswith: str | None = None,
        team_id__endswith: str | None = None,
        team_id__iendswith: str | None = None,
        team_id__iexact: str | None = None,
        team_id__in: list[str] | None = None,
        team_id__isnull: bool | None = None,
        unestimated_handling: <enum 'UnestimatedHandling'> | None = None,
        unestimated_handling__in: list[<enum 'UnestimatedHandling'>] | None = None,
        unestimated_handling__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
    ) -> "OxydeProjectQuery":
        """Exclude objects matching field lookups."""
        ...

    def order_by(self, *fields: Literal["color", "-color", "created_at", "-created_at", "default_sprint_budget", "-default_sprint_budget", "description", "-description", "estimate_scale", "-estimate_scale", "human_rituals_required", "-human_rituals_required", "icon", "-icon", "id", "-id", "issue_count", "-issue_count", "key", "-key", "lead_id", "-lead_id", "name", "-name", "require_estimate_on_claim", "-require_estimate_on_claim", "team_id", "-team_id", "unestimated_handling", "-unestimated_handling", "updated_at", "-updated_at"]) -> "OxydeProjectQuery":
        """Order results by fields."""
        ...

    def limit(self, n: int) -> "OxydeProjectQuery":
        """Limit number of results."""
        ...

    def offset(self, n: int) -> "OxydeProjectQuery":
        """Skip first n results."""
        ...

    def distinct(self, value: bool = True) -> "OxydeProjectQuery":
        """Return distinct results."""
        ...

    def select(self, *fields: Literal["color", "created_at", "default_sprint_budget", "description", "estimate_scale", "human_rituals_required", "icon", "id", "issue_count", "key", "lead_id", "name", "require_estimate_on_claim", "team_id", "unestimated_handling", "updated_at"]) -> "OxydeProjectQuery":
        """Select specific fields."""
        ...

    def join(self, *paths: str) -> "OxydeProjectQuery":
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> "OxydeProjectQuery":
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> "OxydeProjectQuery":
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> "OxydeProjectQuery":
        """Add FOR SHARE lock to query."""
        ...

    def annotate(self, **annotations: Any) -> "OxydeProjectQuery":
        """Add computed fields using aggregate functions."""
        ...

    def group_by(self, *fields: Literal["color", "created_at", "default_sprint_budget", "description", "estimate_scale", "human_rituals_required", "icon", "id", "issue_count", "key", "lead_id", "name", "require_estimate_on_claim", "team_id", "unestimated_handling", "updated_at"]) -> "OxydeProjectQuery":
        """Add GROUP BY clause."""
        ...

    def having(self, *q_exprs: Any, **kwargs: Any) -> "OxydeProjectQuery":
        """Add HAVING clause for filtering grouped results."""
        ...

    def values(self, *fields: Literal["color", "created_at", "default_sprint_budget", "description", "estimate_scale", "human_rituals_required", "icon", "id", "issue_count", "key", "lead_id", "name", "require_estimate_on_claim", "team_id", "unestimated_handling", "updated_at"]) -> "OxydeProjectQuery":
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["color", "created_at", "default_sprint_budget", "description", "estimate_scale", "human_rituals_required", "icon", "id", "issue_count", "key", "lead_id", "name", "require_estimate_on_claim", "team_id", "unestimated_handling", "updated_at"], flat: bool = False) -> "OxydeProjectQuery":
        """Return tuples/values instead of models."""
        ...

    # Terminal methods (async, execute query)

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[OxydeProject]:
        """Execute query and return all results."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> OxydeProject | None:
        """Execute query and return first result."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> OxydeProject | None:
        """Execute query and return last result."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count matching objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def update(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **values: Any,
    ) -> int:
        """Update matching objects."""
        ...

    async def increment(
        self,
        field: str,
        by: int | float = 1,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Atomically increment a field value."""
        ...

    async def delete(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Delete matching objects."""
        ...

class OxydeProjectManager(QueryManager[OxydeProject]):
    """Type-safe Manager for OxydeProject model."""

    # Query building methods (sync, return Query)

    def query(self) -> OxydeProjectQuery:
        """Return a Query builder for this model."""
        ...

    def filter(
        self,
        *args: Any,
        color: str | None = None,
        color__contains: str | None = None,
        color__icontains: str | None = None,
        color__startswith: str | None = None,
        color__istartswith: str | None = None,
        color__endswith: str | None = None,
        color__iendswith: str | None = None,
        color__iexact: str | None = None,
        color__in: list[str] | None = None,
        color__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        default_sprint_budget: int | None = None,
        default_sprint_budget__gt: int | None = None,
        default_sprint_budget__gte: int | None = None,
        default_sprint_budget__lt: int | None = None,
        default_sprint_budget__lte: int | None = None,
        default_sprint_budget__between: tuple[int, int] | None = None,
        default_sprint_budget__range: int | None = None,
        default_sprint_budget__in: list[int] | None = None,
        default_sprint_budget__isnull: bool | None = None,
        description: str | None = None,
        description__contains: str | None = None,
        description__icontains: str | None = None,
        description__startswith: str | None = None,
        description__istartswith: str | None = None,
        description__endswith: str | None = None,
        description__iendswith: str | None = None,
        description__iexact: str | None = None,
        description__in: list[str] | None = None,
        description__isnull: bool | None = None,
        estimate_scale: <enum 'EstimateScale'> | None = None,
        estimate_scale__in: list[<enum 'EstimateScale'>] | None = None,
        estimate_scale__isnull: bool | None = None,
        human_rituals_required: bool | None = None,
        human_rituals_required__in: list[bool] | None = None,
        human_rituals_required__isnull: bool | None = None,
        icon: str | None = None,
        icon__contains: str | None = None,
        icon__icontains: str | None = None,
        icon__startswith: str | None = None,
        icon__istartswith: str | None = None,
        icon__endswith: str | None = None,
        icon__iendswith: str | None = None,
        icon__iexact: str | None = None,
        icon__in: list[str] | None = None,
        icon__isnull: bool | None = None,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        issue_count: int | None = None,
        issue_count__gt: int | None = None,
        issue_count__gte: int | None = None,
        issue_count__lt: int | None = None,
        issue_count__lte: int | None = None,
        issue_count__between: tuple[int, int] | None = None,
        issue_count__range: int | None = None,
        issue_count__in: list[int] | None = None,
        issue_count__isnull: bool | None = None,
        key: str | None = None,
        key__contains: str | None = None,
        key__icontains: str | None = None,
        key__startswith: str | None = None,
        key__istartswith: str | None = None,
        key__endswith: str | None = None,
        key__iendswith: str | None = None,
        key__iexact: str | None = None,
        key__in: list[str] | None = None,
        key__isnull: bool | None = None,
        lead_id: str | None = None,
        lead_id__contains: str | None = None,
        lead_id__icontains: str | None = None,
        lead_id__startswith: str | None = None,
        lead_id__istartswith: str | None = None,
        lead_id__endswith: str | None = None,
        lead_id__iendswith: str | None = None,
        lead_id__iexact: str | None = None,
        lead_id__in: list[str] | None = None,
        lead_id__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        require_estimate_on_claim: bool | None = None,
        require_estimate_on_claim__in: list[bool] | None = None,
        require_estimate_on_claim__isnull: bool | None = None,
        team_id: str | None = None,
        team_id__contains: str | None = None,
        team_id__icontains: str | None = None,
        team_id__startswith: str | None = None,
        team_id__istartswith: str | None = None,
        team_id__endswith: str | None = None,
        team_id__iendswith: str | None = None,
        team_id__iexact: str | None = None,
        team_id__in: list[str] | None = None,
        team_id__isnull: bool | None = None,
        unestimated_handling: <enum 'UnestimatedHandling'> | None = None,
        unestimated_handling__in: list[<enum 'UnestimatedHandling'>] | None = None,
        unestimated_handling__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
    ) -> OxydeProjectQuery:
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        color: str | None = None,
        color__contains: str | None = None,
        color__icontains: str | None = None,
        color__startswith: str | None = None,
        color__istartswith: str | None = None,
        color__endswith: str | None = None,
        color__iendswith: str | None = None,
        color__iexact: str | None = None,
        color__in: list[str] | None = None,
        color__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        default_sprint_budget: int | None = None,
        default_sprint_budget__gt: int | None = None,
        default_sprint_budget__gte: int | None = None,
        default_sprint_budget__lt: int | None = None,
        default_sprint_budget__lte: int | None = None,
        default_sprint_budget__between: tuple[int, int] | None = None,
        default_sprint_budget__range: int | None = None,
        default_sprint_budget__in: list[int] | None = None,
        default_sprint_budget__isnull: bool | None = None,
        description: str | None = None,
        description__contains: str | None = None,
        description__icontains: str | None = None,
        description__startswith: str | None = None,
        description__istartswith: str | None = None,
        description__endswith: str | None = None,
        description__iendswith: str | None = None,
        description__iexact: str | None = None,
        description__in: list[str] | None = None,
        description__isnull: bool | None = None,
        estimate_scale: <enum 'EstimateScale'> | None = None,
        estimate_scale__in: list[<enum 'EstimateScale'>] | None = None,
        estimate_scale__isnull: bool | None = None,
        human_rituals_required: bool | None = None,
        human_rituals_required__in: list[bool] | None = None,
        human_rituals_required__isnull: bool | None = None,
        icon: str | None = None,
        icon__contains: str | None = None,
        icon__icontains: str | None = None,
        icon__startswith: str | None = None,
        icon__istartswith: str | None = None,
        icon__endswith: str | None = None,
        icon__iendswith: str | None = None,
        icon__iexact: str | None = None,
        icon__in: list[str] | None = None,
        icon__isnull: bool | None = None,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        issue_count: int | None = None,
        issue_count__gt: int | None = None,
        issue_count__gte: int | None = None,
        issue_count__lt: int | None = None,
        issue_count__lte: int | None = None,
        issue_count__between: tuple[int, int] | None = None,
        issue_count__range: int | None = None,
        issue_count__in: list[int] | None = None,
        issue_count__isnull: bool | None = None,
        key: str | None = None,
        key__contains: str | None = None,
        key__icontains: str | None = None,
        key__startswith: str | None = None,
        key__istartswith: str | None = None,
        key__endswith: str | None = None,
        key__iendswith: str | None = None,
        key__iexact: str | None = None,
        key__in: list[str] | None = None,
        key__isnull: bool | None = None,
        lead_id: str | None = None,
        lead_id__contains: str | None = None,
        lead_id__icontains: str | None = None,
        lead_id__startswith: str | None = None,
        lead_id__istartswith: str | None = None,
        lead_id__endswith: str | None = None,
        lead_id__iendswith: str | None = None,
        lead_id__iexact: str | None = None,
        lead_id__in: list[str] | None = None,
        lead_id__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        require_estimate_on_claim: bool | None = None,
        require_estimate_on_claim__in: list[bool] | None = None,
        require_estimate_on_claim__isnull: bool | None = None,
        team_id: str | None = None,
        team_id__contains: str | None = None,
        team_id__icontains: str | None = None,
        team_id__startswith: str | None = None,
        team_id__istartswith: str | None = None,
        team_id__endswith: str | None = None,
        team_id__iendswith: str | None = None,
        team_id__iexact: str | None = None,
        team_id__in: list[str] | None = None,
        team_id__isnull: bool | None = None,
        unestimated_handling: <enum 'UnestimatedHandling'> | None = None,
        unestimated_handling__in: list[<enum 'UnestimatedHandling'>] | None = None,
        unestimated_handling__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
    ) -> OxydeProjectQuery:
        """Exclude objects matching field lookups."""
        ...

    def values(self, *fields: Literal["color", "created_at", "default_sprint_budget", "description", "estimate_scale", "human_rituals_required", "icon", "id", "issue_count", "key", "lead_id", "name", "require_estimate_on_claim", "team_id", "unestimated_handling", "updated_at"]) -> OxydeProjectQuery:
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["color", "created_at", "default_sprint_budget", "description", "estimate_scale", "human_rituals_required", "icon", "id", "issue_count", "key", "lead_id", "name", "require_estimate_on_claim", "team_id", "unestimated_handling", "updated_at"], flat: bool = False) -> OxydeProjectQuery:
        """Return tuples/values instead of models."""
        ...

    def distinct(self, distinct: bool = True) -> OxydeProjectQuery:
        """Return distinct results."""
        ...

    def join(self, *paths: str) -> OxydeProjectQuery:
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> OxydeProjectQuery:
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> OxydeProjectQuery:
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> OxydeProjectQuery:
        """Add FOR SHARE lock to query."""
        ...

    # Terminal methods (async, execute query)

    async def get(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> OxydeProject:
        """Get single object matching lookups."""
        ...

    async def get_or_none(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> OxydeProject | None:
        """Get object or None if not found."""
        ...

    async def get_or_create(
        self,
        *,
        defaults: dict[str, Any] | None = None,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> tuple[OxydeProject, bool]:
        """Get object or create if not found. Returns (object, created)."""
        ...

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        mode: str = "models",
    ) -> list[OxydeProject]:
        """Get all objects."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> OxydeProject | None:
        """Get first object."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> OxydeProject | None:
        """Get last object."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count all objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def create(
        self,
        *,
        instance: OxydeProject | None = None,
        client: Any | None = None,
        using: str | None = None,
        color: str | None = None,
        created_at: datetime | None = None,
        default_sprint_budget: int | None = None,
        description: str | None = None,
        estimate_scale: <enum 'EstimateScale'> | None = None,
        human_rituals_required: bool | None = None,
        icon: str | None = None,
        id: str | None = None,
        issue_count: int | None = None,
        key: str | None = None,
        lead_id: str | None = None,
        name: str | None = None,
        require_estimate_on_claim: bool | None = None,
        team_id: str | None = None,
        unestimated_handling: <enum 'UnestimatedHandling'> | None = None,
        updated_at: datetime | None = None,
    ) -> OxydeProject:
        """Create new object."""
        ...

    async def bulk_create(
        self,
        objects: list[OxydeProject],
        *,
        batch_size: int | None = None,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[OxydeProject]:
        """Bulk create objects."""
        ...

    async def bulk_update(
        self,
        objects: list[OxydeProject],
        fields: list[str],
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Bulk update objects."""
        ...
