# Auto-generated by oxyde generate-stubs
# DO NOT EDIT - This file will be overwritten

from typing import Any, Literal
from datetime import datetime, date, time
from decimal import Decimal
from uuid import UUID

from oxyde import OxydeModel
from oxyde.queries import Query, QueryManager


class OxydeRitualGroup(OxydeModel):
    class Meta:
        is_table: bool
        table_name: str
    id: str
    project_id: str
    name: str
    selection_mode: <enum 'SelectionMode'>
    last_selected_ritual_id: str | None
    created_at: datetime
    objects: "OxydeRitualGroupManager"

class OxydeRitual(OxydeModel):
    class Meta:
        is_table: bool
        table_name: str
    id: str
    project_id: str
    name: str
    prompt: str
    trigger: <enum 'RitualTrigger'>
    approval_mode: <enum 'ApprovalMode'>
    note_required: bool
    conditions: str | None
    group: OxydeRitualGroup | None
    weight: float
    percentage: float | None
    created_at: datetime
    updated_at: datetime
    is_active: bool
    group_id: str | None
    objects: "OxydeRitualManager"

class OxydeRitualAttestation(OxydeModel):
    class Meta:
        is_table: bool
        table_name: str
    id: str
    ritual: OxydeRitual | None
    sprint: OxydeSprint | None
    issue: OxydeIssue | None
    attested_by: str | None
    attested_at: datetime
    note: str | None
    approved_by: str | None
    approved_at: datetime | None
    ritual_id: str | None
    sprint_id: str | None
    issue_id: str | None
    objects: "OxydeRitualAttestationManager"


class OxydeRitualGroupQuery(Query[OxydeRitualGroup]):
    """Type-safe Query for OxydeRitualGroup model."""

    # Query building methods (sync, return Query)

    def filter(
        self,
        *args: Any,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        last_selected_ritual_id: str | None = None,
        last_selected_ritual_id__contains: str | None = None,
        last_selected_ritual_id__icontains: str | None = None,
        last_selected_ritual_id__startswith: str | None = None,
        last_selected_ritual_id__istartswith: str | None = None,
        last_selected_ritual_id__endswith: str | None = None,
        last_selected_ritual_id__iendswith: str | None = None,
        last_selected_ritual_id__iexact: str | None = None,
        last_selected_ritual_id__in: list[str] | None = None,
        last_selected_ritual_id__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        project_id: str | None = None,
        project_id__contains: str | None = None,
        project_id__icontains: str | None = None,
        project_id__startswith: str | None = None,
        project_id__istartswith: str | None = None,
        project_id__endswith: str | None = None,
        project_id__iendswith: str | None = None,
        project_id__iexact: str | None = None,
        project_id__in: list[str] | None = None,
        project_id__isnull: bool | None = None,
        selection_mode: <enum 'SelectionMode'> | None = None,
        selection_mode__in: list[<enum 'SelectionMode'>] | None = None,
        selection_mode__isnull: bool | None = None,
    ) -> "OxydeRitualGroupQuery":
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        last_selected_ritual_id: str | None = None,
        last_selected_ritual_id__contains: str | None = None,
        last_selected_ritual_id__icontains: str | None = None,
        last_selected_ritual_id__startswith: str | None = None,
        last_selected_ritual_id__istartswith: str | None = None,
        last_selected_ritual_id__endswith: str | None = None,
        last_selected_ritual_id__iendswith: str | None = None,
        last_selected_ritual_id__iexact: str | None = None,
        last_selected_ritual_id__in: list[str] | None = None,
        last_selected_ritual_id__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        project_id: str | None = None,
        project_id__contains: str | None = None,
        project_id__icontains: str | None = None,
        project_id__startswith: str | None = None,
        project_id__istartswith: str | None = None,
        project_id__endswith: str | None = None,
        project_id__iendswith: str | None = None,
        project_id__iexact: str | None = None,
        project_id__in: list[str] | None = None,
        project_id__isnull: bool | None = None,
        selection_mode: <enum 'SelectionMode'> | None = None,
        selection_mode__in: list[<enum 'SelectionMode'>] | None = None,
        selection_mode__isnull: bool | None = None,
    ) -> "OxydeRitualGroupQuery":
        """Exclude objects matching field lookups."""
        ...

    def order_by(self, *fields: Literal["created_at", "-created_at", "id", "-id", "last_selected_ritual_id", "-last_selected_ritual_id", "name", "-name", "project_id", "-project_id", "selection_mode", "-selection_mode"]) -> "OxydeRitualGroupQuery":
        """Order results by fields."""
        ...

    def limit(self, n: int) -> "OxydeRitualGroupQuery":
        """Limit number of results."""
        ...

    def offset(self, n: int) -> "OxydeRitualGroupQuery":
        """Skip first n results."""
        ...

    def distinct(self, value: bool = True) -> "OxydeRitualGroupQuery":
        """Return distinct results."""
        ...

    def select(self, *fields: Literal["created_at", "id", "last_selected_ritual_id", "name", "project_id", "selection_mode"]) -> "OxydeRitualGroupQuery":
        """Select specific fields."""
        ...

    def join(self, *paths: str) -> "OxydeRitualGroupQuery":
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> "OxydeRitualGroupQuery":
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> "OxydeRitualGroupQuery":
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> "OxydeRitualGroupQuery":
        """Add FOR SHARE lock to query."""
        ...

    def annotate(self, **annotations: Any) -> "OxydeRitualGroupQuery":
        """Add computed fields using aggregate functions."""
        ...

    def group_by(self, *fields: Literal["created_at", "id", "last_selected_ritual_id", "name", "project_id", "selection_mode"]) -> "OxydeRitualGroupQuery":
        """Add GROUP BY clause."""
        ...

    def having(self, *q_exprs: Any, **kwargs: Any) -> "OxydeRitualGroupQuery":
        """Add HAVING clause for filtering grouped results."""
        ...

    def values(self, *fields: Literal["created_at", "id", "last_selected_ritual_id", "name", "project_id", "selection_mode"]) -> "OxydeRitualGroupQuery":
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["created_at", "id", "last_selected_ritual_id", "name", "project_id", "selection_mode"], flat: bool = False) -> "OxydeRitualGroupQuery":
        """Return tuples/values instead of models."""
        ...

    # Terminal methods (async, execute query)

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[OxydeRitualGroup]:
        """Execute query and return all results."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> OxydeRitualGroup | None:
        """Execute query and return first result."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> OxydeRitualGroup | None:
        """Execute query and return last result."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count matching objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def update(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **values: Any,
    ) -> int:
        """Update matching objects."""
        ...

    async def increment(
        self,
        field: str,
        by: int | float = 1,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Atomically increment a field value."""
        ...

    async def delete(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Delete matching objects."""
        ...

class OxydeRitualGroupManager(QueryManager[OxydeRitualGroup]):
    """Type-safe Manager for OxydeRitualGroup model."""

    # Query building methods (sync, return Query)

    def query(self) -> OxydeRitualGroupQuery:
        """Return a Query builder for this model."""
        ...

    def filter(
        self,
        *args: Any,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        last_selected_ritual_id: str | None = None,
        last_selected_ritual_id__contains: str | None = None,
        last_selected_ritual_id__icontains: str | None = None,
        last_selected_ritual_id__startswith: str | None = None,
        last_selected_ritual_id__istartswith: str | None = None,
        last_selected_ritual_id__endswith: str | None = None,
        last_selected_ritual_id__iendswith: str | None = None,
        last_selected_ritual_id__iexact: str | None = None,
        last_selected_ritual_id__in: list[str] | None = None,
        last_selected_ritual_id__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        project_id: str | None = None,
        project_id__contains: str | None = None,
        project_id__icontains: str | None = None,
        project_id__startswith: str | None = None,
        project_id__istartswith: str | None = None,
        project_id__endswith: str | None = None,
        project_id__iendswith: str | None = None,
        project_id__iexact: str | None = None,
        project_id__in: list[str] | None = None,
        project_id__isnull: bool | None = None,
        selection_mode: <enum 'SelectionMode'> | None = None,
        selection_mode__in: list[<enum 'SelectionMode'>] | None = None,
        selection_mode__isnull: bool | None = None,
    ) -> OxydeRitualGroupQuery:
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        last_selected_ritual_id: str | None = None,
        last_selected_ritual_id__contains: str | None = None,
        last_selected_ritual_id__icontains: str | None = None,
        last_selected_ritual_id__startswith: str | None = None,
        last_selected_ritual_id__istartswith: str | None = None,
        last_selected_ritual_id__endswith: str | None = None,
        last_selected_ritual_id__iendswith: str | None = None,
        last_selected_ritual_id__iexact: str | None = None,
        last_selected_ritual_id__in: list[str] | None = None,
        last_selected_ritual_id__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        project_id: str | None = None,
        project_id__contains: str | None = None,
        project_id__icontains: str | None = None,
        project_id__startswith: str | None = None,
        project_id__istartswith: str | None = None,
        project_id__endswith: str | None = None,
        project_id__iendswith: str | None = None,
        project_id__iexact: str | None = None,
        project_id__in: list[str] | None = None,
        project_id__isnull: bool | None = None,
        selection_mode: <enum 'SelectionMode'> | None = None,
        selection_mode__in: list[<enum 'SelectionMode'>] | None = None,
        selection_mode__isnull: bool | None = None,
    ) -> OxydeRitualGroupQuery:
        """Exclude objects matching field lookups."""
        ...

    def values(self, *fields: Literal["created_at", "id", "last_selected_ritual_id", "name", "project_id", "selection_mode"]) -> OxydeRitualGroupQuery:
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["created_at", "id", "last_selected_ritual_id", "name", "project_id", "selection_mode"], flat: bool = False) -> OxydeRitualGroupQuery:
        """Return tuples/values instead of models."""
        ...

    def distinct(self, distinct: bool = True) -> OxydeRitualGroupQuery:
        """Return distinct results."""
        ...

    def join(self, *paths: str) -> OxydeRitualGroupQuery:
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> OxydeRitualGroupQuery:
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> OxydeRitualGroupQuery:
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> OxydeRitualGroupQuery:
        """Add FOR SHARE lock to query."""
        ...

    # Terminal methods (async, execute query)

    async def get(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> OxydeRitualGroup:
        """Get single object matching lookups."""
        ...

    async def get_or_none(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> OxydeRitualGroup | None:
        """Get object or None if not found."""
        ...

    async def get_or_create(
        self,
        *,
        defaults: dict[str, Any] | None = None,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> tuple[OxydeRitualGroup, bool]:
        """Get object or create if not found. Returns (object, created)."""
        ...

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        mode: str = "models",
    ) -> list[OxydeRitualGroup]:
        """Get all objects."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> OxydeRitualGroup | None:
        """Get first object."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> OxydeRitualGroup | None:
        """Get last object."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count all objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def create(
        self,
        *,
        instance: OxydeRitualGroup | None = None,
        client: Any | None = None,
        using: str | None = None,
        created_at: datetime | None = None,
        id: str | None = None,
        last_selected_ritual_id: str | None = None,
        name: str | None = None,
        project_id: str | None = None,
        selection_mode: <enum 'SelectionMode'> | None = None,
    ) -> OxydeRitualGroup:
        """Create new object."""
        ...

    async def bulk_create(
        self,
        objects: list[OxydeRitualGroup],
        *,
        batch_size: int | None = None,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[OxydeRitualGroup]:
        """Bulk create objects."""
        ...

    async def bulk_update(
        self,
        objects: list[OxydeRitualGroup],
        fields: list[str],
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Bulk update objects."""
        ...



class OxydeRitualQuery(Query[OxydeRitual]):
    """Type-safe Query for OxydeRitual model."""

    # Query building methods (sync, return Query)

    def filter(
        self,
        *args: Any,
        approval_mode: <enum 'ApprovalMode'> | None = None,
        approval_mode__in: list[<enum 'ApprovalMode'>] | None = None,
        approval_mode__isnull: bool | None = None,
        conditions: str | None = None,
        conditions__contains: str | None = None,
        conditions__icontains: str | None = None,
        conditions__startswith: str | None = None,
        conditions__istartswith: str | None = None,
        conditions__endswith: str | None = None,
        conditions__iendswith: str | None = None,
        conditions__iexact: str | None = None,
        conditions__in: list[str] | None = None,
        conditions__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        group: OxydeRitualGroup | None = None,
        group__in: list[OxydeRitualGroup] | None = None,
        group__isnull: bool | None = None,
        group_id: str | None = None,
        group_id__contains: str | None = None,
        group_id__icontains: str | None = None,
        group_id__startswith: str | None = None,
        group_id__istartswith: str | None = None,
        group_id__endswith: str | None = None,
        group_id__iendswith: str | None = None,
        group_id__iexact: str | None = None,
        group_id__in: list[str] | None = None,
        group_id__isnull: bool | None = None,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        is_active: bool | None = None,
        is_active__in: list[bool] | None = None,
        is_active__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        note_required: bool | None = None,
        note_required__in: list[bool] | None = None,
        note_required__isnull: bool | None = None,
        percentage: float | None = None,
        percentage__gt: float | None = None,
        percentage__gte: float | None = None,
        percentage__lt: float | None = None,
        percentage__lte: float | None = None,
        percentage__between: tuple[float, float] | None = None,
        percentage__range: float | None = None,
        percentage__in: list[float] | None = None,
        percentage__isnull: bool | None = None,
        project_id: str | None = None,
        project_id__contains: str | None = None,
        project_id__icontains: str | None = None,
        project_id__startswith: str | None = None,
        project_id__istartswith: str | None = None,
        project_id__endswith: str | None = None,
        project_id__iendswith: str | None = None,
        project_id__iexact: str | None = None,
        project_id__in: list[str] | None = None,
        project_id__isnull: bool | None = None,
        prompt: str | None = None,
        prompt__contains: str | None = None,
        prompt__icontains: str | None = None,
        prompt__startswith: str | None = None,
        prompt__istartswith: str | None = None,
        prompt__endswith: str | None = None,
        prompt__iendswith: str | None = None,
        prompt__iexact: str | None = None,
        prompt__in: list[str] | None = None,
        prompt__isnull: bool | None = None,
        trigger: <enum 'RitualTrigger'> | None = None,
        trigger__in: list[<enum 'RitualTrigger'>] | None = None,
        trigger__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
        weight: float | None = None,
        weight__gt: float | None = None,
        weight__gte: float | None = None,
        weight__lt: float | None = None,
        weight__lte: float | None = None,
        weight__between: tuple[float, float] | None = None,
        weight__range: float | None = None,
        weight__in: list[float] | None = None,
        weight__isnull: bool | None = None,
    ) -> "OxydeRitualQuery":
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        approval_mode: <enum 'ApprovalMode'> | None = None,
        approval_mode__in: list[<enum 'ApprovalMode'>] | None = None,
        approval_mode__isnull: bool | None = None,
        conditions: str | None = None,
        conditions__contains: str | None = None,
        conditions__icontains: str | None = None,
        conditions__startswith: str | None = None,
        conditions__istartswith: str | None = None,
        conditions__endswith: str | None = None,
        conditions__iendswith: str | None = None,
        conditions__iexact: str | None = None,
        conditions__in: list[str] | None = None,
        conditions__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        group: OxydeRitualGroup | None = None,
        group__in: list[OxydeRitualGroup] | None = None,
        group__isnull: bool | None = None,
        group_id: str | None = None,
        group_id__contains: str | None = None,
        group_id__icontains: str | None = None,
        group_id__startswith: str | None = None,
        group_id__istartswith: str | None = None,
        group_id__endswith: str | None = None,
        group_id__iendswith: str | None = None,
        group_id__iexact: str | None = None,
        group_id__in: list[str] | None = None,
        group_id__isnull: bool | None = None,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        is_active: bool | None = None,
        is_active__in: list[bool] | None = None,
        is_active__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        note_required: bool | None = None,
        note_required__in: list[bool] | None = None,
        note_required__isnull: bool | None = None,
        percentage: float | None = None,
        percentage__gt: float | None = None,
        percentage__gte: float | None = None,
        percentage__lt: float | None = None,
        percentage__lte: float | None = None,
        percentage__between: tuple[float, float] | None = None,
        percentage__range: float | None = None,
        percentage__in: list[float] | None = None,
        percentage__isnull: bool | None = None,
        project_id: str | None = None,
        project_id__contains: str | None = None,
        project_id__icontains: str | None = None,
        project_id__startswith: str | None = None,
        project_id__istartswith: str | None = None,
        project_id__endswith: str | None = None,
        project_id__iendswith: str | None = None,
        project_id__iexact: str | None = None,
        project_id__in: list[str] | None = None,
        project_id__isnull: bool | None = None,
        prompt: str | None = None,
        prompt__contains: str | None = None,
        prompt__icontains: str | None = None,
        prompt__startswith: str | None = None,
        prompt__istartswith: str | None = None,
        prompt__endswith: str | None = None,
        prompt__iendswith: str | None = None,
        prompt__iexact: str | None = None,
        prompt__in: list[str] | None = None,
        prompt__isnull: bool | None = None,
        trigger: <enum 'RitualTrigger'> | None = None,
        trigger__in: list[<enum 'RitualTrigger'>] | None = None,
        trigger__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
        weight: float | None = None,
        weight__gt: float | None = None,
        weight__gte: float | None = None,
        weight__lt: float | None = None,
        weight__lte: float | None = None,
        weight__between: tuple[float, float] | None = None,
        weight__range: float | None = None,
        weight__in: list[float] | None = None,
        weight__isnull: bool | None = None,
    ) -> "OxydeRitualQuery":
        """Exclude objects matching field lookups."""
        ...

    def order_by(self, *fields: Literal["approval_mode", "-approval_mode", "conditions", "-conditions", "created_at", "-created_at", "group", "-group", "group_id", "-group_id", "id", "-id", "is_active", "-is_active", "name", "-name", "note_required", "-note_required", "percentage", "-percentage", "project_id", "-project_id", "prompt", "-prompt", "trigger", "-trigger", "updated_at", "-updated_at", "weight", "-weight"]) -> "OxydeRitualQuery":
        """Order results by fields."""
        ...

    def limit(self, n: int) -> "OxydeRitualQuery":
        """Limit number of results."""
        ...

    def offset(self, n: int) -> "OxydeRitualQuery":
        """Skip first n results."""
        ...

    def distinct(self, value: bool = True) -> "OxydeRitualQuery":
        """Return distinct results."""
        ...

    def select(self, *fields: Literal["approval_mode", "conditions", "created_at", "group", "group_id", "id", "is_active", "name", "note_required", "percentage", "project_id", "prompt", "trigger", "updated_at", "weight"]) -> "OxydeRitualQuery":
        """Select specific fields."""
        ...

    def join(self, *paths: str) -> "OxydeRitualQuery":
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> "OxydeRitualQuery":
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> "OxydeRitualQuery":
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> "OxydeRitualQuery":
        """Add FOR SHARE lock to query."""
        ...

    def annotate(self, **annotations: Any) -> "OxydeRitualQuery":
        """Add computed fields using aggregate functions."""
        ...

    def group_by(self, *fields: Literal["approval_mode", "conditions", "created_at", "group", "group_id", "id", "is_active", "name", "note_required", "percentage", "project_id", "prompt", "trigger", "updated_at", "weight"]) -> "OxydeRitualQuery":
        """Add GROUP BY clause."""
        ...

    def having(self, *q_exprs: Any, **kwargs: Any) -> "OxydeRitualQuery":
        """Add HAVING clause for filtering grouped results."""
        ...

    def values(self, *fields: Literal["approval_mode", "conditions", "created_at", "group", "group_id", "id", "is_active", "name", "note_required", "percentage", "project_id", "prompt", "trigger", "updated_at", "weight"]) -> "OxydeRitualQuery":
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["approval_mode", "conditions", "created_at", "group", "group_id", "id", "is_active", "name", "note_required", "percentage", "project_id", "prompt", "trigger", "updated_at", "weight"], flat: bool = False) -> "OxydeRitualQuery":
        """Return tuples/values instead of models."""
        ...

    # Terminal methods (async, execute query)

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[OxydeRitual]:
        """Execute query and return all results."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> OxydeRitual | None:
        """Execute query and return first result."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> OxydeRitual | None:
        """Execute query and return last result."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count matching objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def update(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **values: Any,
    ) -> int:
        """Update matching objects."""
        ...

    async def increment(
        self,
        field: str,
        by: int | float = 1,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Atomically increment a field value."""
        ...

    async def delete(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Delete matching objects."""
        ...

class OxydeRitualManager(QueryManager[OxydeRitual]):
    """Type-safe Manager for OxydeRitual model."""

    # Query building methods (sync, return Query)

    def query(self) -> OxydeRitualQuery:
        """Return a Query builder for this model."""
        ...

    def filter(
        self,
        *args: Any,
        approval_mode: <enum 'ApprovalMode'> | None = None,
        approval_mode__in: list[<enum 'ApprovalMode'>] | None = None,
        approval_mode__isnull: bool | None = None,
        conditions: str | None = None,
        conditions__contains: str | None = None,
        conditions__icontains: str | None = None,
        conditions__startswith: str | None = None,
        conditions__istartswith: str | None = None,
        conditions__endswith: str | None = None,
        conditions__iendswith: str | None = None,
        conditions__iexact: str | None = None,
        conditions__in: list[str] | None = None,
        conditions__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        group: OxydeRitualGroup | None = None,
        group__in: list[OxydeRitualGroup] | None = None,
        group__isnull: bool | None = None,
        group_id: str | None = None,
        group_id__contains: str | None = None,
        group_id__icontains: str | None = None,
        group_id__startswith: str | None = None,
        group_id__istartswith: str | None = None,
        group_id__endswith: str | None = None,
        group_id__iendswith: str | None = None,
        group_id__iexact: str | None = None,
        group_id__in: list[str] | None = None,
        group_id__isnull: bool | None = None,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        is_active: bool | None = None,
        is_active__in: list[bool] | None = None,
        is_active__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        note_required: bool | None = None,
        note_required__in: list[bool] | None = None,
        note_required__isnull: bool | None = None,
        percentage: float | None = None,
        percentage__gt: float | None = None,
        percentage__gte: float | None = None,
        percentage__lt: float | None = None,
        percentage__lte: float | None = None,
        percentage__between: tuple[float, float] | None = None,
        percentage__range: float | None = None,
        percentage__in: list[float] | None = None,
        percentage__isnull: bool | None = None,
        project_id: str | None = None,
        project_id__contains: str | None = None,
        project_id__icontains: str | None = None,
        project_id__startswith: str | None = None,
        project_id__istartswith: str | None = None,
        project_id__endswith: str | None = None,
        project_id__iendswith: str | None = None,
        project_id__iexact: str | None = None,
        project_id__in: list[str] | None = None,
        project_id__isnull: bool | None = None,
        prompt: str | None = None,
        prompt__contains: str | None = None,
        prompt__icontains: str | None = None,
        prompt__startswith: str | None = None,
        prompt__istartswith: str | None = None,
        prompt__endswith: str | None = None,
        prompt__iendswith: str | None = None,
        prompt__iexact: str | None = None,
        prompt__in: list[str] | None = None,
        prompt__isnull: bool | None = None,
        trigger: <enum 'RitualTrigger'> | None = None,
        trigger__in: list[<enum 'RitualTrigger'>] | None = None,
        trigger__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
        weight: float | None = None,
        weight__gt: float | None = None,
        weight__gte: float | None = None,
        weight__lt: float | None = None,
        weight__lte: float | None = None,
        weight__between: tuple[float, float] | None = None,
        weight__range: float | None = None,
        weight__in: list[float] | None = None,
        weight__isnull: bool | None = None,
    ) -> OxydeRitualQuery:
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        approval_mode: <enum 'ApprovalMode'> | None = None,
        approval_mode__in: list[<enum 'ApprovalMode'>] | None = None,
        approval_mode__isnull: bool | None = None,
        conditions: str | None = None,
        conditions__contains: str | None = None,
        conditions__icontains: str | None = None,
        conditions__startswith: str | None = None,
        conditions__istartswith: str | None = None,
        conditions__endswith: str | None = None,
        conditions__iendswith: str | None = None,
        conditions__iexact: str | None = None,
        conditions__in: list[str] | None = None,
        conditions__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        group: OxydeRitualGroup | None = None,
        group__in: list[OxydeRitualGroup] | None = None,
        group__isnull: bool | None = None,
        group_id: str | None = None,
        group_id__contains: str | None = None,
        group_id__icontains: str | None = None,
        group_id__startswith: str | None = None,
        group_id__istartswith: str | None = None,
        group_id__endswith: str | None = None,
        group_id__iendswith: str | None = None,
        group_id__iexact: str | None = None,
        group_id__in: list[str] | None = None,
        group_id__isnull: bool | None = None,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        is_active: bool | None = None,
        is_active__in: list[bool] | None = None,
        is_active__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        note_required: bool | None = None,
        note_required__in: list[bool] | None = None,
        note_required__isnull: bool | None = None,
        percentage: float | None = None,
        percentage__gt: float | None = None,
        percentage__gte: float | None = None,
        percentage__lt: float | None = None,
        percentage__lte: float | None = None,
        percentage__between: tuple[float, float] | None = None,
        percentage__range: float | None = None,
        percentage__in: list[float] | None = None,
        percentage__isnull: bool | None = None,
        project_id: str | None = None,
        project_id__contains: str | None = None,
        project_id__icontains: str | None = None,
        project_id__startswith: str | None = None,
        project_id__istartswith: str | None = None,
        project_id__endswith: str | None = None,
        project_id__iendswith: str | None = None,
        project_id__iexact: str | None = None,
        project_id__in: list[str] | None = None,
        project_id__isnull: bool | None = None,
        prompt: str | None = None,
        prompt__contains: str | None = None,
        prompt__icontains: str | None = None,
        prompt__startswith: str | None = None,
        prompt__istartswith: str | None = None,
        prompt__endswith: str | None = None,
        prompt__iendswith: str | None = None,
        prompt__iexact: str | None = None,
        prompt__in: list[str] | None = None,
        prompt__isnull: bool | None = None,
        trigger: <enum 'RitualTrigger'> | None = None,
        trigger__in: list[<enum 'RitualTrigger'>] | None = None,
        trigger__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
        weight: float | None = None,
        weight__gt: float | None = None,
        weight__gte: float | None = None,
        weight__lt: float | None = None,
        weight__lte: float | None = None,
        weight__between: tuple[float, float] | None = None,
        weight__range: float | None = None,
        weight__in: list[float] | None = None,
        weight__isnull: bool | None = None,
    ) -> OxydeRitualQuery:
        """Exclude objects matching field lookups."""
        ...

    def values(self, *fields: Literal["approval_mode", "conditions", "created_at", "group", "group_id", "id", "is_active", "name", "note_required", "percentage", "project_id", "prompt", "trigger", "updated_at", "weight"]) -> OxydeRitualQuery:
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["approval_mode", "conditions", "created_at", "group", "group_id", "id", "is_active", "name", "note_required", "percentage", "project_id", "prompt", "trigger", "updated_at", "weight"], flat: bool = False) -> OxydeRitualQuery:
        """Return tuples/values instead of models."""
        ...

    def distinct(self, distinct: bool = True) -> OxydeRitualQuery:
        """Return distinct results."""
        ...

    def join(self, *paths: str) -> OxydeRitualQuery:
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> OxydeRitualQuery:
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> OxydeRitualQuery:
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> OxydeRitualQuery:
        """Add FOR SHARE lock to query."""
        ...

    # Terminal methods (async, execute query)

    async def get(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> OxydeRitual:
        """Get single object matching lookups."""
        ...

    async def get_or_none(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> OxydeRitual | None:
        """Get object or None if not found."""
        ...

    async def get_or_create(
        self,
        *,
        defaults: dict[str, Any] | None = None,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> tuple[OxydeRitual, bool]:
        """Get object or create if not found. Returns (object, created)."""
        ...

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        mode: str = "models",
    ) -> list[OxydeRitual]:
        """Get all objects."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> OxydeRitual | None:
        """Get first object."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> OxydeRitual | None:
        """Get last object."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count all objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def create(
        self,
        *,
        instance: OxydeRitual | None = None,
        client: Any | None = None,
        using: str | None = None,
        approval_mode: <enum 'ApprovalMode'> | None = None,
        conditions: str | None = None,
        created_at: datetime | None = None,
        group: OxydeRitualGroup | None = None,
        group_id: str | None = None,
        id: str | None = None,
        is_active: bool | None = None,
        name: str | None = None,
        note_required: bool | None = None,
        percentage: float | None = None,
        project_id: str | None = None,
        prompt: str | None = None,
        trigger: <enum 'RitualTrigger'> | None = None,
        updated_at: datetime | None = None,
        weight: float | None = None,
    ) -> OxydeRitual:
        """Create new object."""
        ...

    async def bulk_create(
        self,
        objects: list[OxydeRitual],
        *,
        batch_size: int | None = None,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[OxydeRitual]:
        """Bulk create objects."""
        ...

    async def bulk_update(
        self,
        objects: list[OxydeRitual],
        fields: list[str],
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Bulk update objects."""
        ...



class OxydeRitualAttestationQuery(Query[OxydeRitualAttestation]):
    """Type-safe Query for OxydeRitualAttestation model."""

    # Query building methods (sync, return Query)

    def filter(
        self,
        *args: Any,
        approved_at: datetime | None = None,
        approved_at__gt: datetime | None = None,
        approved_at__gte: datetime | None = None,
        approved_at__lt: datetime | None = None,
        approved_at__lte: datetime | None = None,
        approved_at__between: tuple[datetime, datetime] | None = None,
        approved_at__range: datetime | None = None,
        approved_at__year: int | None = None,
        approved_at__month: int | None = None,
        approved_at__day: int | None = None,
        approved_at__in: list[datetime] | None = None,
        approved_at__isnull: bool | None = None,
        approved_by: str | None = None,
        approved_by__contains: str | None = None,
        approved_by__icontains: str | None = None,
        approved_by__startswith: str | None = None,
        approved_by__istartswith: str | None = None,
        approved_by__endswith: str | None = None,
        approved_by__iendswith: str | None = None,
        approved_by__iexact: str | None = None,
        approved_by__in: list[str] | None = None,
        approved_by__isnull: bool | None = None,
        attested_at: datetime | None = None,
        attested_at__gt: datetime | None = None,
        attested_at__gte: datetime | None = None,
        attested_at__lt: datetime | None = None,
        attested_at__lte: datetime | None = None,
        attested_at__between: tuple[datetime, datetime] | None = None,
        attested_at__range: datetime | None = None,
        attested_at__year: int | None = None,
        attested_at__month: int | None = None,
        attested_at__day: int | None = None,
        attested_at__in: list[datetime] | None = None,
        attested_at__isnull: bool | None = None,
        attested_by: str | None = None,
        attested_by__contains: str | None = None,
        attested_by__icontains: str | None = None,
        attested_by__startswith: str | None = None,
        attested_by__istartswith: str | None = None,
        attested_by__endswith: str | None = None,
        attested_by__iendswith: str | None = None,
        attested_by__iexact: str | None = None,
        attested_by__in: list[str] | None = None,
        attested_by__isnull: bool | None = None,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        issue: OxydeIssue | None = None,
        issue__in: list[OxydeIssue] | None = None,
        issue__isnull: bool | None = None,
        issue_id: str | None = None,
        issue_id__contains: str | None = None,
        issue_id__icontains: str | None = None,
        issue_id__startswith: str | None = None,
        issue_id__istartswith: str | None = None,
        issue_id__endswith: str | None = None,
        issue_id__iendswith: str | None = None,
        issue_id__iexact: str | None = None,
        issue_id__in: list[str] | None = None,
        issue_id__isnull: bool | None = None,
        note: str | None = None,
        note__contains: str | None = None,
        note__icontains: str | None = None,
        note__startswith: str | None = None,
        note__istartswith: str | None = None,
        note__endswith: str | None = None,
        note__iendswith: str | None = None,
        note__iexact: str | None = None,
        note__in: list[str] | None = None,
        note__isnull: bool | None = None,
        ritual: OxydeRitual | None = None,
        ritual__in: list[OxydeRitual] | None = None,
        ritual__isnull: bool | None = None,
        ritual_id: str | None = None,
        ritual_id__contains: str | None = None,
        ritual_id__icontains: str | None = None,
        ritual_id__startswith: str | None = None,
        ritual_id__istartswith: str | None = None,
        ritual_id__endswith: str | None = None,
        ritual_id__iendswith: str | None = None,
        ritual_id__iexact: str | None = None,
        ritual_id__in: list[str] | None = None,
        ritual_id__isnull: bool | None = None,
        sprint: OxydeSprint | None = None,
        sprint__in: list[OxydeSprint] | None = None,
        sprint__isnull: bool | None = None,
        sprint_id: str | None = None,
        sprint_id__contains: str | None = None,
        sprint_id__icontains: str | None = None,
        sprint_id__startswith: str | None = None,
        sprint_id__istartswith: str | None = None,
        sprint_id__endswith: str | None = None,
        sprint_id__iendswith: str | None = None,
        sprint_id__iexact: str | None = None,
        sprint_id__in: list[str] | None = None,
        sprint_id__isnull: bool | None = None,
    ) -> "OxydeRitualAttestationQuery":
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        approved_at: datetime | None = None,
        approved_at__gt: datetime | None = None,
        approved_at__gte: datetime | None = None,
        approved_at__lt: datetime | None = None,
        approved_at__lte: datetime | None = None,
        approved_at__between: tuple[datetime, datetime] | None = None,
        approved_at__range: datetime | None = None,
        approved_at__year: int | None = None,
        approved_at__month: int | None = None,
        approved_at__day: int | None = None,
        approved_at__in: list[datetime] | None = None,
        approved_at__isnull: bool | None = None,
        approved_by: str | None = None,
        approved_by__contains: str | None = None,
        approved_by__icontains: str | None = None,
        approved_by__startswith: str | None = None,
        approved_by__istartswith: str | None = None,
        approved_by__endswith: str | None = None,
        approved_by__iendswith: str | None = None,
        approved_by__iexact: str | None = None,
        approved_by__in: list[str] | None = None,
        approved_by__isnull: bool | None = None,
        attested_at: datetime | None = None,
        attested_at__gt: datetime | None = None,
        attested_at__gte: datetime | None = None,
        attested_at__lt: datetime | None = None,
        attested_at__lte: datetime | None = None,
        attested_at__between: tuple[datetime, datetime] | None = None,
        attested_at__range: datetime | None = None,
        attested_at__year: int | None = None,
        attested_at__month: int | None = None,
        attested_at__day: int | None = None,
        attested_at__in: list[datetime] | None = None,
        attested_at__isnull: bool | None = None,
        attested_by: str | None = None,
        attested_by__contains: str | None = None,
        attested_by__icontains: str | None = None,
        attested_by__startswith: str | None = None,
        attested_by__istartswith: str | None = None,
        attested_by__endswith: str | None = None,
        attested_by__iendswith: str | None = None,
        attested_by__iexact: str | None = None,
        attested_by__in: list[str] | None = None,
        attested_by__isnull: bool | None = None,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        issue: OxydeIssue | None = None,
        issue__in: list[OxydeIssue] | None = None,
        issue__isnull: bool | None = None,
        issue_id: str | None = None,
        issue_id__contains: str | None = None,
        issue_id__icontains: str | None = None,
        issue_id__startswith: str | None = None,
        issue_id__istartswith: str | None = None,
        issue_id__endswith: str | None = None,
        issue_id__iendswith: str | None = None,
        issue_id__iexact: str | None = None,
        issue_id__in: list[str] | None = None,
        issue_id__isnull: bool | None = None,
        note: str | None = None,
        note__contains: str | None = None,
        note__icontains: str | None = None,
        note__startswith: str | None = None,
        note__istartswith: str | None = None,
        note__endswith: str | None = None,
        note__iendswith: str | None = None,
        note__iexact: str | None = None,
        note__in: list[str] | None = None,
        note__isnull: bool | None = None,
        ritual: OxydeRitual | None = None,
        ritual__in: list[OxydeRitual] | None = None,
        ritual__isnull: bool | None = None,
        ritual_id: str | None = None,
        ritual_id__contains: str | None = None,
        ritual_id__icontains: str | None = None,
        ritual_id__startswith: str | None = None,
        ritual_id__istartswith: str | None = None,
        ritual_id__endswith: str | None = None,
        ritual_id__iendswith: str | None = None,
        ritual_id__iexact: str | None = None,
        ritual_id__in: list[str] | None = None,
        ritual_id__isnull: bool | None = None,
        sprint: OxydeSprint | None = None,
        sprint__in: list[OxydeSprint] | None = None,
        sprint__isnull: bool | None = None,
        sprint_id: str | None = None,
        sprint_id__contains: str | None = None,
        sprint_id__icontains: str | None = None,
        sprint_id__startswith: str | None = None,
        sprint_id__istartswith: str | None = None,
        sprint_id__endswith: str | None = None,
        sprint_id__iendswith: str | None = None,
        sprint_id__iexact: str | None = None,
        sprint_id__in: list[str] | None = None,
        sprint_id__isnull: bool | None = None,
    ) -> "OxydeRitualAttestationQuery":
        """Exclude objects matching field lookups."""
        ...

    def order_by(self, *fields: Literal["approved_at", "-approved_at", "approved_by", "-approved_by", "attested_at", "-attested_at", "attested_by", "-attested_by", "id", "-id", "issue", "-issue", "issue_id", "-issue_id", "note", "-note", "ritual", "-ritual", "ritual_id", "-ritual_id", "sprint", "-sprint", "sprint_id", "-sprint_id"]) -> "OxydeRitualAttestationQuery":
        """Order results by fields."""
        ...

    def limit(self, n: int) -> "OxydeRitualAttestationQuery":
        """Limit number of results."""
        ...

    def offset(self, n: int) -> "OxydeRitualAttestationQuery":
        """Skip first n results."""
        ...

    def distinct(self, value: bool = True) -> "OxydeRitualAttestationQuery":
        """Return distinct results."""
        ...

    def select(self, *fields: Literal["approved_at", "approved_by", "attested_at", "attested_by", "id", "issue", "issue_id", "note", "ritual", "ritual_id", "sprint", "sprint_id"]) -> "OxydeRitualAttestationQuery":
        """Select specific fields."""
        ...

    def join(self, *paths: str) -> "OxydeRitualAttestationQuery":
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> "OxydeRitualAttestationQuery":
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> "OxydeRitualAttestationQuery":
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> "OxydeRitualAttestationQuery":
        """Add FOR SHARE lock to query."""
        ...

    def annotate(self, **annotations: Any) -> "OxydeRitualAttestationQuery":
        """Add computed fields using aggregate functions."""
        ...

    def group_by(self, *fields: Literal["approved_at", "approved_by", "attested_at", "attested_by", "id", "issue", "issue_id", "note", "ritual", "ritual_id", "sprint", "sprint_id"]) -> "OxydeRitualAttestationQuery":
        """Add GROUP BY clause."""
        ...

    def having(self, *q_exprs: Any, **kwargs: Any) -> "OxydeRitualAttestationQuery":
        """Add HAVING clause for filtering grouped results."""
        ...

    def values(self, *fields: Literal["approved_at", "approved_by", "attested_at", "attested_by", "id", "issue", "issue_id", "note", "ritual", "ritual_id", "sprint", "sprint_id"]) -> "OxydeRitualAttestationQuery":
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["approved_at", "approved_by", "attested_at", "attested_by", "id", "issue", "issue_id", "note", "ritual", "ritual_id", "sprint", "sprint_id"], flat: bool = False) -> "OxydeRitualAttestationQuery":
        """Return tuples/values instead of models."""
        ...

    # Terminal methods (async, execute query)

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[OxydeRitualAttestation]:
        """Execute query and return all results."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> OxydeRitualAttestation | None:
        """Execute query and return first result."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> OxydeRitualAttestation | None:
        """Execute query and return last result."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count matching objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def update(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **values: Any,
    ) -> int:
        """Update matching objects."""
        ...

    async def increment(
        self,
        field: str,
        by: int | float = 1,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Atomically increment a field value."""
        ...

    async def delete(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Delete matching objects."""
        ...

class OxydeRitualAttestationManager(QueryManager[OxydeRitualAttestation]):
    """Type-safe Manager for OxydeRitualAttestation model."""

    # Query building methods (sync, return Query)

    def query(self) -> OxydeRitualAttestationQuery:
        """Return a Query builder for this model."""
        ...

    def filter(
        self,
        *args: Any,
        approved_at: datetime | None = None,
        approved_at__gt: datetime | None = None,
        approved_at__gte: datetime | None = None,
        approved_at__lt: datetime | None = None,
        approved_at__lte: datetime | None = None,
        approved_at__between: tuple[datetime, datetime] | None = None,
        approved_at__range: datetime | None = None,
        approved_at__year: int | None = None,
        approved_at__month: int | None = None,
        approved_at__day: int | None = None,
        approved_at__in: list[datetime] | None = None,
        approved_at__isnull: bool | None = None,
        approved_by: str | None = None,
        approved_by__contains: str | None = None,
        approved_by__icontains: str | None = None,
        approved_by__startswith: str | None = None,
        approved_by__istartswith: str | None = None,
        approved_by__endswith: str | None = None,
        approved_by__iendswith: str | None = None,
        approved_by__iexact: str | None = None,
        approved_by__in: list[str] | None = None,
        approved_by__isnull: bool | None = None,
        attested_at: datetime | None = None,
        attested_at__gt: datetime | None = None,
        attested_at__gte: datetime | None = None,
        attested_at__lt: datetime | None = None,
        attested_at__lte: datetime | None = None,
        attested_at__between: tuple[datetime, datetime] | None = None,
        attested_at__range: datetime | None = None,
        attested_at__year: int | None = None,
        attested_at__month: int | None = None,
        attested_at__day: int | None = None,
        attested_at__in: list[datetime] | None = None,
        attested_at__isnull: bool | None = None,
        attested_by: str | None = None,
        attested_by__contains: str | None = None,
        attested_by__icontains: str | None = None,
        attested_by__startswith: str | None = None,
        attested_by__istartswith: str | None = None,
        attested_by__endswith: str | None = None,
        attested_by__iendswith: str | None = None,
        attested_by__iexact: str | None = None,
        attested_by__in: list[str] | None = None,
        attested_by__isnull: bool | None = None,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        issue: OxydeIssue | None = None,
        issue__in: list[OxydeIssue] | None = None,
        issue__isnull: bool | None = None,
        issue_id: str | None = None,
        issue_id__contains: str | None = None,
        issue_id__icontains: str | None = None,
        issue_id__startswith: str | None = None,
        issue_id__istartswith: str | None = None,
        issue_id__endswith: str | None = None,
        issue_id__iendswith: str | None = None,
        issue_id__iexact: str | None = None,
        issue_id__in: list[str] | None = None,
        issue_id__isnull: bool | None = None,
        note: str | None = None,
        note__contains: str | None = None,
        note__icontains: str | None = None,
        note__startswith: str | None = None,
        note__istartswith: str | None = None,
        note__endswith: str | None = None,
        note__iendswith: str | None = None,
        note__iexact: str | None = None,
        note__in: list[str] | None = None,
        note__isnull: bool | None = None,
        ritual: OxydeRitual | None = None,
        ritual__in: list[OxydeRitual] | None = None,
        ritual__isnull: bool | None = None,
        ritual_id: str | None = None,
        ritual_id__contains: str | None = None,
        ritual_id__icontains: str | None = None,
        ritual_id__startswith: str | None = None,
        ritual_id__istartswith: str | None = None,
        ritual_id__endswith: str | None = None,
        ritual_id__iendswith: str | None = None,
        ritual_id__iexact: str | None = None,
        ritual_id__in: list[str] | None = None,
        ritual_id__isnull: bool | None = None,
        sprint: OxydeSprint | None = None,
        sprint__in: list[OxydeSprint] | None = None,
        sprint__isnull: bool | None = None,
        sprint_id: str | None = None,
        sprint_id__contains: str | None = None,
        sprint_id__icontains: str | None = None,
        sprint_id__startswith: str | None = None,
        sprint_id__istartswith: str | None = None,
        sprint_id__endswith: str | None = None,
        sprint_id__iendswith: str | None = None,
        sprint_id__iexact: str | None = None,
        sprint_id__in: list[str] | None = None,
        sprint_id__isnull: bool | None = None,
    ) -> OxydeRitualAttestationQuery:
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        approved_at: datetime | None = None,
        approved_at__gt: datetime | None = None,
        approved_at__gte: datetime | None = None,
        approved_at__lt: datetime | None = None,
        approved_at__lte: datetime | None = None,
        approved_at__between: tuple[datetime, datetime] | None = None,
        approved_at__range: datetime | None = None,
        approved_at__year: int | None = None,
        approved_at__month: int | None = None,
        approved_at__day: int | None = None,
        approved_at__in: list[datetime] | None = None,
        approved_at__isnull: bool | None = None,
        approved_by: str | None = None,
        approved_by__contains: str | None = None,
        approved_by__icontains: str | None = None,
        approved_by__startswith: str | None = None,
        approved_by__istartswith: str | None = None,
        approved_by__endswith: str | None = None,
        approved_by__iendswith: str | None = None,
        approved_by__iexact: str | None = None,
        approved_by__in: list[str] | None = None,
        approved_by__isnull: bool | None = None,
        attested_at: datetime | None = None,
        attested_at__gt: datetime | None = None,
        attested_at__gte: datetime | None = None,
        attested_at__lt: datetime | None = None,
        attested_at__lte: datetime | None = None,
        attested_at__between: tuple[datetime, datetime] | None = None,
        attested_at__range: datetime | None = None,
        attested_at__year: int | None = None,
        attested_at__month: int | None = None,
        attested_at__day: int | None = None,
        attested_at__in: list[datetime] | None = None,
        attested_at__isnull: bool | None = None,
        attested_by: str | None = None,
        attested_by__contains: str | None = None,
        attested_by__icontains: str | None = None,
        attested_by__startswith: str | None = None,
        attested_by__istartswith: str | None = None,
        attested_by__endswith: str | None = None,
        attested_by__iendswith: str | None = None,
        attested_by__iexact: str | None = None,
        attested_by__in: list[str] | None = None,
        attested_by__isnull: bool | None = None,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        issue: OxydeIssue | None = None,
        issue__in: list[OxydeIssue] | None = None,
        issue__isnull: bool | None = None,
        issue_id: str | None = None,
        issue_id__contains: str | None = None,
        issue_id__icontains: str | None = None,
        issue_id__startswith: str | None = None,
        issue_id__istartswith: str | None = None,
        issue_id__endswith: str | None = None,
        issue_id__iendswith: str | None = None,
        issue_id__iexact: str | None = None,
        issue_id__in: list[str] | None = None,
        issue_id__isnull: bool | None = None,
        note: str | None = None,
        note__contains: str | None = None,
        note__icontains: str | None = None,
        note__startswith: str | None = None,
        note__istartswith: str | None = None,
        note__endswith: str | None = None,
        note__iendswith: str | None = None,
        note__iexact: str | None = None,
        note__in: list[str] | None = None,
        note__isnull: bool | None = None,
        ritual: OxydeRitual | None = None,
        ritual__in: list[OxydeRitual] | None = None,
        ritual__isnull: bool | None = None,
        ritual_id: str | None = None,
        ritual_id__contains: str | None = None,
        ritual_id__icontains: str | None = None,
        ritual_id__startswith: str | None = None,
        ritual_id__istartswith: str | None = None,
        ritual_id__endswith: str | None = None,
        ritual_id__iendswith: str | None = None,
        ritual_id__iexact: str | None = None,
        ritual_id__in: list[str] | None = None,
        ritual_id__isnull: bool | None = None,
        sprint: OxydeSprint | None = None,
        sprint__in: list[OxydeSprint] | None = None,
        sprint__isnull: bool | None = None,
        sprint_id: str | None = None,
        sprint_id__contains: str | None = None,
        sprint_id__icontains: str | None = None,
        sprint_id__startswith: str | None = None,
        sprint_id__istartswith: str | None = None,
        sprint_id__endswith: str | None = None,
        sprint_id__iendswith: str | None = None,
        sprint_id__iexact: str | None = None,
        sprint_id__in: list[str] | None = None,
        sprint_id__isnull: bool | None = None,
    ) -> OxydeRitualAttestationQuery:
        """Exclude objects matching field lookups."""
        ...

    def values(self, *fields: Literal["approved_at", "approved_by", "attested_at", "attested_by", "id", "issue", "issue_id", "note", "ritual", "ritual_id", "sprint", "sprint_id"]) -> OxydeRitualAttestationQuery:
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["approved_at", "approved_by", "attested_at", "attested_by", "id", "issue", "issue_id", "note", "ritual", "ritual_id", "sprint", "sprint_id"], flat: bool = False) -> OxydeRitualAttestationQuery:
        """Return tuples/values instead of models."""
        ...

    def distinct(self, distinct: bool = True) -> OxydeRitualAttestationQuery:
        """Return distinct results."""
        ...

    def join(self, *paths: str) -> OxydeRitualAttestationQuery:
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> OxydeRitualAttestationQuery:
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> OxydeRitualAttestationQuery:
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> OxydeRitualAttestationQuery:
        """Add FOR SHARE lock to query."""
        ...

    # Terminal methods (async, execute query)

    async def get(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> OxydeRitualAttestation:
        """Get single object matching lookups."""
        ...

    async def get_or_none(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> OxydeRitualAttestation | None:
        """Get object or None if not found."""
        ...

    async def get_or_create(
        self,
        *,
        defaults: dict[str, Any] | None = None,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> tuple[OxydeRitualAttestation, bool]:
        """Get object or create if not found. Returns (object, created)."""
        ...

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        mode: str = "models",
    ) -> list[OxydeRitualAttestation]:
        """Get all objects."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> OxydeRitualAttestation | None:
        """Get first object."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> OxydeRitualAttestation | None:
        """Get last object."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count all objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def create(
        self,
        *,
        instance: OxydeRitualAttestation | None = None,
        client: Any | None = None,
        using: str | None = None,
        approved_at: datetime | None = None,
        approved_by: str | None = None,
        attested_at: datetime | None = None,
        attested_by: str | None = None,
        id: str | None = None,
        issue: OxydeIssue | None = None,
        issue_id: str | None = None,
        note: str | None = None,
        ritual: OxydeRitual | None = None,
        ritual_id: str | None = None,
        sprint: OxydeSprint | None = None,
        sprint_id: str | None = None,
    ) -> OxydeRitualAttestation:
        """Create new object."""
        ...

    async def bulk_create(
        self,
        objects: list[OxydeRitualAttestation],
        *,
        batch_size: int | None = None,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[OxydeRitualAttestation]:
        """Bulk create objects."""
        ...

    async def bulk_update(
        self,
        objects: list[OxydeRitualAttestation],
        fields: list[str],
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Bulk update objects."""
        ...
