# Auto-generated by oxyde generate-stubs
# DO NOT EDIT - This file will be overwritten

from typing import Any, Literal
from datetime import datetime, date, time
from decimal import Decimal
from uuid import UUID

from oxyde import OxydeModel
from oxyde.queries import Query, QueryManager


class OxydeSprint(OxydeModel):
    class Meta:
        is_table: bool
        table_name: str
    id: str
    project_id: str
    name: str
    description: str | None
    status: <enum 'SprintStatus'>
    start_date: datetime | None
    end_date: datetime | None
    budget: int | None
    points_spent: int
    token_budget: int | None
    tokens_spent: int
    limbo: bool
    created_at: datetime
    updated_at: datetime
    objects: "OxydeSprintManager"


class OxydeSprintQuery(Query[OxydeSprint]):
    """Type-safe Query for OxydeSprint model."""

    # Query building methods (sync, return Query)

    def filter(
        self,
        *args: Any,
        budget: int | None = None,
        budget__gt: int | None = None,
        budget__gte: int | None = None,
        budget__lt: int | None = None,
        budget__lte: int | None = None,
        budget__between: tuple[int, int] | None = None,
        budget__range: int | None = None,
        budget__in: list[int] | None = None,
        budget__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        description: str | None = None,
        description__contains: str | None = None,
        description__icontains: str | None = None,
        description__startswith: str | None = None,
        description__istartswith: str | None = None,
        description__endswith: str | None = None,
        description__iendswith: str | None = None,
        description__iexact: str | None = None,
        description__in: list[str] | None = None,
        description__isnull: bool | None = None,
        end_date: datetime | None = None,
        end_date__gt: datetime | None = None,
        end_date__gte: datetime | None = None,
        end_date__lt: datetime | None = None,
        end_date__lte: datetime | None = None,
        end_date__between: tuple[datetime, datetime] | None = None,
        end_date__range: datetime | None = None,
        end_date__year: int | None = None,
        end_date__month: int | None = None,
        end_date__day: int | None = None,
        end_date__in: list[datetime] | None = None,
        end_date__isnull: bool | None = None,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        limbo: bool | None = None,
        limbo__in: list[bool] | None = None,
        limbo__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        points_spent: int | None = None,
        points_spent__gt: int | None = None,
        points_spent__gte: int | None = None,
        points_spent__lt: int | None = None,
        points_spent__lte: int | None = None,
        points_spent__between: tuple[int, int] | None = None,
        points_spent__range: int | None = None,
        points_spent__in: list[int] | None = None,
        points_spent__isnull: bool | None = None,
        project_id: str | None = None,
        project_id__contains: str | None = None,
        project_id__icontains: str | None = None,
        project_id__startswith: str | None = None,
        project_id__istartswith: str | None = None,
        project_id__endswith: str | None = None,
        project_id__iendswith: str | None = None,
        project_id__iexact: str | None = None,
        project_id__in: list[str] | None = None,
        project_id__isnull: bool | None = None,
        start_date: datetime | None = None,
        start_date__gt: datetime | None = None,
        start_date__gte: datetime | None = None,
        start_date__lt: datetime | None = None,
        start_date__lte: datetime | None = None,
        start_date__between: tuple[datetime, datetime] | None = None,
        start_date__range: datetime | None = None,
        start_date__year: int | None = None,
        start_date__month: int | None = None,
        start_date__day: int | None = None,
        start_date__in: list[datetime] | None = None,
        start_date__isnull: bool | None = None,
        status: <enum 'SprintStatus'> | None = None,
        status__in: list[<enum 'SprintStatus'>] | None = None,
        status__isnull: bool | None = None,
        token_budget: int | None = None,
        token_budget__gt: int | None = None,
        token_budget__gte: int | None = None,
        token_budget__lt: int | None = None,
        token_budget__lte: int | None = None,
        token_budget__between: tuple[int, int] | None = None,
        token_budget__range: int | None = None,
        token_budget__in: list[int] | None = None,
        token_budget__isnull: bool | None = None,
        tokens_spent: int | None = None,
        tokens_spent__gt: int | None = None,
        tokens_spent__gte: int | None = None,
        tokens_spent__lt: int | None = None,
        tokens_spent__lte: int | None = None,
        tokens_spent__between: tuple[int, int] | None = None,
        tokens_spent__range: int | None = None,
        tokens_spent__in: list[int] | None = None,
        tokens_spent__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
    ) -> "OxydeSprintQuery":
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        budget: int | None = None,
        budget__gt: int | None = None,
        budget__gte: int | None = None,
        budget__lt: int | None = None,
        budget__lte: int | None = None,
        budget__between: tuple[int, int] | None = None,
        budget__range: int | None = None,
        budget__in: list[int] | None = None,
        budget__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        description: str | None = None,
        description__contains: str | None = None,
        description__icontains: str | None = None,
        description__startswith: str | None = None,
        description__istartswith: str | None = None,
        description__endswith: str | None = None,
        description__iendswith: str | None = None,
        description__iexact: str | None = None,
        description__in: list[str] | None = None,
        description__isnull: bool | None = None,
        end_date: datetime | None = None,
        end_date__gt: datetime | None = None,
        end_date__gte: datetime | None = None,
        end_date__lt: datetime | None = None,
        end_date__lte: datetime | None = None,
        end_date__between: tuple[datetime, datetime] | None = None,
        end_date__range: datetime | None = None,
        end_date__year: int | None = None,
        end_date__month: int | None = None,
        end_date__day: int | None = None,
        end_date__in: list[datetime] | None = None,
        end_date__isnull: bool | None = None,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        limbo: bool | None = None,
        limbo__in: list[bool] | None = None,
        limbo__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        points_spent: int | None = None,
        points_spent__gt: int | None = None,
        points_spent__gte: int | None = None,
        points_spent__lt: int | None = None,
        points_spent__lte: int | None = None,
        points_spent__between: tuple[int, int] | None = None,
        points_spent__range: int | None = None,
        points_spent__in: list[int] | None = None,
        points_spent__isnull: bool | None = None,
        project_id: str | None = None,
        project_id__contains: str | None = None,
        project_id__icontains: str | None = None,
        project_id__startswith: str | None = None,
        project_id__istartswith: str | None = None,
        project_id__endswith: str | None = None,
        project_id__iendswith: str | None = None,
        project_id__iexact: str | None = None,
        project_id__in: list[str] | None = None,
        project_id__isnull: bool | None = None,
        start_date: datetime | None = None,
        start_date__gt: datetime | None = None,
        start_date__gte: datetime | None = None,
        start_date__lt: datetime | None = None,
        start_date__lte: datetime | None = None,
        start_date__between: tuple[datetime, datetime] | None = None,
        start_date__range: datetime | None = None,
        start_date__year: int | None = None,
        start_date__month: int | None = None,
        start_date__day: int | None = None,
        start_date__in: list[datetime] | None = None,
        start_date__isnull: bool | None = None,
        status: <enum 'SprintStatus'> | None = None,
        status__in: list[<enum 'SprintStatus'>] | None = None,
        status__isnull: bool | None = None,
        token_budget: int | None = None,
        token_budget__gt: int | None = None,
        token_budget__gte: int | None = None,
        token_budget__lt: int | None = None,
        token_budget__lte: int | None = None,
        token_budget__between: tuple[int, int] | None = None,
        token_budget__range: int | None = None,
        token_budget__in: list[int] | None = None,
        token_budget__isnull: bool | None = None,
        tokens_spent: int | None = None,
        tokens_spent__gt: int | None = None,
        tokens_spent__gte: int | None = None,
        tokens_spent__lt: int | None = None,
        tokens_spent__lte: int | None = None,
        tokens_spent__between: tuple[int, int] | None = None,
        tokens_spent__range: int | None = None,
        tokens_spent__in: list[int] | None = None,
        tokens_spent__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
    ) -> "OxydeSprintQuery":
        """Exclude objects matching field lookups."""
        ...

    def order_by(self, *fields: Literal["budget", "-budget", "created_at", "-created_at", "description", "-description", "end_date", "-end_date", "id", "-id", "limbo", "-limbo", "name", "-name", "points_spent", "-points_spent", "project_id", "-project_id", "start_date", "-start_date", "status", "-status", "token_budget", "-token_budget", "tokens_spent", "-tokens_spent", "updated_at", "-updated_at"]) -> "OxydeSprintQuery":
        """Order results by fields."""
        ...

    def limit(self, n: int) -> "OxydeSprintQuery":
        """Limit number of results."""
        ...

    def offset(self, n: int) -> "OxydeSprintQuery":
        """Skip first n results."""
        ...

    def distinct(self, value: bool = True) -> "OxydeSprintQuery":
        """Return distinct results."""
        ...

    def select(self, *fields: Literal["budget", "created_at", "description", "end_date", "id", "limbo", "name", "points_spent", "project_id", "start_date", "status", "token_budget", "tokens_spent", "updated_at"]) -> "OxydeSprintQuery":
        """Select specific fields."""
        ...

    def join(self, *paths: str) -> "OxydeSprintQuery":
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> "OxydeSprintQuery":
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> "OxydeSprintQuery":
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> "OxydeSprintQuery":
        """Add FOR SHARE lock to query."""
        ...

    def annotate(self, **annotations: Any) -> "OxydeSprintQuery":
        """Add computed fields using aggregate functions."""
        ...

    def group_by(self, *fields: Literal["budget", "created_at", "description", "end_date", "id", "limbo", "name", "points_spent", "project_id", "start_date", "status", "token_budget", "tokens_spent", "updated_at"]) -> "OxydeSprintQuery":
        """Add GROUP BY clause."""
        ...

    def having(self, *q_exprs: Any, **kwargs: Any) -> "OxydeSprintQuery":
        """Add HAVING clause for filtering grouped results."""
        ...

    def values(self, *fields: Literal["budget", "created_at", "description", "end_date", "id", "limbo", "name", "points_spent", "project_id", "start_date", "status", "token_budget", "tokens_spent", "updated_at"]) -> "OxydeSprintQuery":
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["budget", "created_at", "description", "end_date", "id", "limbo", "name", "points_spent", "project_id", "start_date", "status", "token_budget", "tokens_spent", "updated_at"], flat: bool = False) -> "OxydeSprintQuery":
        """Return tuples/values instead of models."""
        ...

    # Terminal methods (async, execute query)

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[OxydeSprint]:
        """Execute query and return all results."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> OxydeSprint | None:
        """Execute query and return first result."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> OxydeSprint | None:
        """Execute query and return last result."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count matching objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def update(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **values: Any,
    ) -> int:
        """Update matching objects."""
        ...

    async def increment(
        self,
        field: str,
        by: int | float = 1,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Atomically increment a field value."""
        ...

    async def delete(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Delete matching objects."""
        ...

class OxydeSprintManager(QueryManager[OxydeSprint]):
    """Type-safe Manager for OxydeSprint model."""

    # Query building methods (sync, return Query)

    def query(self) -> OxydeSprintQuery:
        """Return a Query builder for this model."""
        ...

    def filter(
        self,
        *args: Any,
        budget: int | None = None,
        budget__gt: int | None = None,
        budget__gte: int | None = None,
        budget__lt: int | None = None,
        budget__lte: int | None = None,
        budget__between: tuple[int, int] | None = None,
        budget__range: int | None = None,
        budget__in: list[int] | None = None,
        budget__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        description: str | None = None,
        description__contains: str | None = None,
        description__icontains: str | None = None,
        description__startswith: str | None = None,
        description__istartswith: str | None = None,
        description__endswith: str | None = None,
        description__iendswith: str | None = None,
        description__iexact: str | None = None,
        description__in: list[str] | None = None,
        description__isnull: bool | None = None,
        end_date: datetime | None = None,
        end_date__gt: datetime | None = None,
        end_date__gte: datetime | None = None,
        end_date__lt: datetime | None = None,
        end_date__lte: datetime | None = None,
        end_date__between: tuple[datetime, datetime] | None = None,
        end_date__range: datetime | None = None,
        end_date__year: int | None = None,
        end_date__month: int | None = None,
        end_date__day: int | None = None,
        end_date__in: list[datetime] | None = None,
        end_date__isnull: bool | None = None,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        limbo: bool | None = None,
        limbo__in: list[bool] | None = None,
        limbo__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        points_spent: int | None = None,
        points_spent__gt: int | None = None,
        points_spent__gte: int | None = None,
        points_spent__lt: int | None = None,
        points_spent__lte: int | None = None,
        points_spent__between: tuple[int, int] | None = None,
        points_spent__range: int | None = None,
        points_spent__in: list[int] | None = None,
        points_spent__isnull: bool | None = None,
        project_id: str | None = None,
        project_id__contains: str | None = None,
        project_id__icontains: str | None = None,
        project_id__startswith: str | None = None,
        project_id__istartswith: str | None = None,
        project_id__endswith: str | None = None,
        project_id__iendswith: str | None = None,
        project_id__iexact: str | None = None,
        project_id__in: list[str] | None = None,
        project_id__isnull: bool | None = None,
        start_date: datetime | None = None,
        start_date__gt: datetime | None = None,
        start_date__gte: datetime | None = None,
        start_date__lt: datetime | None = None,
        start_date__lte: datetime | None = None,
        start_date__between: tuple[datetime, datetime] | None = None,
        start_date__range: datetime | None = None,
        start_date__year: int | None = None,
        start_date__month: int | None = None,
        start_date__day: int | None = None,
        start_date__in: list[datetime] | None = None,
        start_date__isnull: bool | None = None,
        status: <enum 'SprintStatus'> | None = None,
        status__in: list[<enum 'SprintStatus'>] | None = None,
        status__isnull: bool | None = None,
        token_budget: int | None = None,
        token_budget__gt: int | None = None,
        token_budget__gte: int | None = None,
        token_budget__lt: int | None = None,
        token_budget__lte: int | None = None,
        token_budget__between: tuple[int, int] | None = None,
        token_budget__range: int | None = None,
        token_budget__in: list[int] | None = None,
        token_budget__isnull: bool | None = None,
        tokens_spent: int | None = None,
        tokens_spent__gt: int | None = None,
        tokens_spent__gte: int | None = None,
        tokens_spent__lt: int | None = None,
        tokens_spent__lte: int | None = None,
        tokens_spent__between: tuple[int, int] | None = None,
        tokens_spent__range: int | None = None,
        tokens_spent__in: list[int] | None = None,
        tokens_spent__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
    ) -> OxydeSprintQuery:
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        budget: int | None = None,
        budget__gt: int | None = None,
        budget__gte: int | None = None,
        budget__lt: int | None = None,
        budget__lte: int | None = None,
        budget__between: tuple[int, int] | None = None,
        budget__range: int | None = None,
        budget__in: list[int] | None = None,
        budget__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        description: str | None = None,
        description__contains: str | None = None,
        description__icontains: str | None = None,
        description__startswith: str | None = None,
        description__istartswith: str | None = None,
        description__endswith: str | None = None,
        description__iendswith: str | None = None,
        description__iexact: str | None = None,
        description__in: list[str] | None = None,
        description__isnull: bool | None = None,
        end_date: datetime | None = None,
        end_date__gt: datetime | None = None,
        end_date__gte: datetime | None = None,
        end_date__lt: datetime | None = None,
        end_date__lte: datetime | None = None,
        end_date__between: tuple[datetime, datetime] | None = None,
        end_date__range: datetime | None = None,
        end_date__year: int | None = None,
        end_date__month: int | None = None,
        end_date__day: int | None = None,
        end_date__in: list[datetime] | None = None,
        end_date__isnull: bool | None = None,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        limbo: bool | None = None,
        limbo__in: list[bool] | None = None,
        limbo__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        points_spent: int | None = None,
        points_spent__gt: int | None = None,
        points_spent__gte: int | None = None,
        points_spent__lt: int | None = None,
        points_spent__lte: int | None = None,
        points_spent__between: tuple[int, int] | None = None,
        points_spent__range: int | None = None,
        points_spent__in: list[int] | None = None,
        points_spent__isnull: bool | None = None,
        project_id: str | None = None,
        project_id__contains: str | None = None,
        project_id__icontains: str | None = None,
        project_id__startswith: str | None = None,
        project_id__istartswith: str | None = None,
        project_id__endswith: str | None = None,
        project_id__iendswith: str | None = None,
        project_id__iexact: str | None = None,
        project_id__in: list[str] | None = None,
        project_id__isnull: bool | None = None,
        start_date: datetime | None = None,
        start_date__gt: datetime | None = None,
        start_date__gte: datetime | None = None,
        start_date__lt: datetime | None = None,
        start_date__lte: datetime | None = None,
        start_date__between: tuple[datetime, datetime] | None = None,
        start_date__range: datetime | None = None,
        start_date__year: int | None = None,
        start_date__month: int | None = None,
        start_date__day: int | None = None,
        start_date__in: list[datetime] | None = None,
        start_date__isnull: bool | None = None,
        status: <enum 'SprintStatus'> | None = None,
        status__in: list[<enum 'SprintStatus'>] | None = None,
        status__isnull: bool | None = None,
        token_budget: int | None = None,
        token_budget__gt: int | None = None,
        token_budget__gte: int | None = None,
        token_budget__lt: int | None = None,
        token_budget__lte: int | None = None,
        token_budget__between: tuple[int, int] | None = None,
        token_budget__range: int | None = None,
        token_budget__in: list[int] | None = None,
        token_budget__isnull: bool | None = None,
        tokens_spent: int | None = None,
        tokens_spent__gt: int | None = None,
        tokens_spent__gte: int | None = None,
        tokens_spent__lt: int | None = None,
        tokens_spent__lte: int | None = None,
        tokens_spent__between: tuple[int, int] | None = None,
        tokens_spent__range: int | None = None,
        tokens_spent__in: list[int] | None = None,
        tokens_spent__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
    ) -> OxydeSprintQuery:
        """Exclude objects matching field lookups."""
        ...

    def values(self, *fields: Literal["budget", "created_at", "description", "end_date", "id", "limbo", "name", "points_spent", "project_id", "start_date", "status", "token_budget", "tokens_spent", "updated_at"]) -> OxydeSprintQuery:
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["budget", "created_at", "description", "end_date", "id", "limbo", "name", "points_spent", "project_id", "start_date", "status", "token_budget", "tokens_spent", "updated_at"], flat: bool = False) -> OxydeSprintQuery:
        """Return tuples/values instead of models."""
        ...

    def distinct(self, distinct: bool = True) -> OxydeSprintQuery:
        """Return distinct results."""
        ...

    def join(self, *paths: str) -> OxydeSprintQuery:
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> OxydeSprintQuery:
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> OxydeSprintQuery:
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> OxydeSprintQuery:
        """Add FOR SHARE lock to query."""
        ...

    # Terminal methods (async, execute query)

    async def get(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> OxydeSprint:
        """Get single object matching lookups."""
        ...

    async def get_or_none(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> OxydeSprint | None:
        """Get object or None if not found."""
        ...

    async def get_or_create(
        self,
        *,
        defaults: dict[str, Any] | None = None,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> tuple[OxydeSprint, bool]:
        """Get object or create if not found. Returns (object, created)."""
        ...

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        mode: str = "models",
    ) -> list[OxydeSprint]:
        """Get all objects."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> OxydeSprint | None:
        """Get first object."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> OxydeSprint | None:
        """Get last object."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count all objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def create(
        self,
        *,
        instance: OxydeSprint | None = None,
        client: Any | None = None,
        using: str | None = None,
        budget: int | None = None,
        created_at: datetime | None = None,
        description: str | None = None,
        end_date: datetime | None = None,
        id: str | None = None,
        limbo: bool | None = None,
        name: str | None = None,
        points_spent: int | None = None,
        project_id: str | None = None,
        start_date: datetime | None = None,
        status: <enum 'SprintStatus'> | None = None,
        token_budget: int | None = None,
        tokens_spent: int | None = None,
        updated_at: datetime | None = None,
    ) -> OxydeSprint:
        """Create new object."""
        ...

    async def bulk_create(
        self,
        objects: list[OxydeSprint],
        *,
        batch_size: int | None = None,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[OxydeSprint]:
        """Bulk create objects."""
        ...

    async def bulk_update(
        self,
        objects: list[OxydeSprint],
        fields: list[str],
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Bulk update objects."""
        ...
