# Auto-generated by oxyde generate-stubs
# DO NOT EDIT - This file will be overwritten

from typing import Any, Literal
from datetime import datetime, date, time
from decimal import Decimal
from uuid import UUID

from oxyde import OxydeModel
from oxyde.queries import Query, QueryManager


class OxydeTeam(OxydeModel):
    class Meta:
        is_table: bool
        table_name: str
    id: str
    name: str
    key: str
    description: str | None
    logo_url: str | None
    created_at: datetime
    updated_at: datetime
    objects: "OxydeTeamManager"

class OxydeTeamMember(OxydeModel):
    class Meta:
        is_table: bool
        table_name: str
    id: str
    team_id: str
    user: OxydeUser | None
    role: <enum 'TeamRole'>
    joined_at: datetime
    user_id: str | None
    objects: "OxydeTeamMemberManager"

class OxydeTeamInvitation(OxydeModel):
    class Meta:
        is_table: bool
        table_name: str
    id: str
    team_id: str
    email: str
    role: <enum 'TeamRole'>
    token: str
    invited_by: OxydeUser | None
    status: <enum 'InvitationStatus'>
    created_at: datetime
    expires_at: datetime
    invited_by_id: str | None
    objects: "OxydeTeamInvitationManager"


class OxydeTeamQuery(Query[OxydeTeam]):
    """Type-safe Query for OxydeTeam model."""

    # Query building methods (sync, return Query)

    def filter(
        self,
        *args: Any,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        description: str | None = None,
        description__contains: str | None = None,
        description__icontains: str | None = None,
        description__startswith: str | None = None,
        description__istartswith: str | None = None,
        description__endswith: str | None = None,
        description__iendswith: str | None = None,
        description__iexact: str | None = None,
        description__in: list[str] | None = None,
        description__isnull: bool | None = None,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        key: str | None = None,
        key__contains: str | None = None,
        key__icontains: str | None = None,
        key__startswith: str | None = None,
        key__istartswith: str | None = None,
        key__endswith: str | None = None,
        key__iendswith: str | None = None,
        key__iexact: str | None = None,
        key__in: list[str] | None = None,
        key__isnull: bool | None = None,
        logo_url: str | None = None,
        logo_url__contains: str | None = None,
        logo_url__icontains: str | None = None,
        logo_url__startswith: str | None = None,
        logo_url__istartswith: str | None = None,
        logo_url__endswith: str | None = None,
        logo_url__iendswith: str | None = None,
        logo_url__iexact: str | None = None,
        logo_url__in: list[str] | None = None,
        logo_url__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
    ) -> "OxydeTeamQuery":
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        description: str | None = None,
        description__contains: str | None = None,
        description__icontains: str | None = None,
        description__startswith: str | None = None,
        description__istartswith: str | None = None,
        description__endswith: str | None = None,
        description__iendswith: str | None = None,
        description__iexact: str | None = None,
        description__in: list[str] | None = None,
        description__isnull: bool | None = None,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        key: str | None = None,
        key__contains: str | None = None,
        key__icontains: str | None = None,
        key__startswith: str | None = None,
        key__istartswith: str | None = None,
        key__endswith: str | None = None,
        key__iendswith: str | None = None,
        key__iexact: str | None = None,
        key__in: list[str] | None = None,
        key__isnull: bool | None = None,
        logo_url: str | None = None,
        logo_url__contains: str | None = None,
        logo_url__icontains: str | None = None,
        logo_url__startswith: str | None = None,
        logo_url__istartswith: str | None = None,
        logo_url__endswith: str | None = None,
        logo_url__iendswith: str | None = None,
        logo_url__iexact: str | None = None,
        logo_url__in: list[str] | None = None,
        logo_url__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
    ) -> "OxydeTeamQuery":
        """Exclude objects matching field lookups."""
        ...

    def order_by(self, *fields: Literal["created_at", "-created_at", "description", "-description", "id", "-id", "key", "-key", "logo_url", "-logo_url", "name", "-name", "updated_at", "-updated_at"]) -> "OxydeTeamQuery":
        """Order results by fields."""
        ...

    def limit(self, n: int) -> "OxydeTeamQuery":
        """Limit number of results."""
        ...

    def offset(self, n: int) -> "OxydeTeamQuery":
        """Skip first n results."""
        ...

    def distinct(self, value: bool = True) -> "OxydeTeamQuery":
        """Return distinct results."""
        ...

    def select(self, *fields: Literal["created_at", "description", "id", "key", "logo_url", "name", "updated_at"]) -> "OxydeTeamQuery":
        """Select specific fields."""
        ...

    def join(self, *paths: str) -> "OxydeTeamQuery":
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> "OxydeTeamQuery":
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> "OxydeTeamQuery":
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> "OxydeTeamQuery":
        """Add FOR SHARE lock to query."""
        ...

    def annotate(self, **annotations: Any) -> "OxydeTeamQuery":
        """Add computed fields using aggregate functions."""
        ...

    def group_by(self, *fields: Literal["created_at", "description", "id", "key", "logo_url", "name", "updated_at"]) -> "OxydeTeamQuery":
        """Add GROUP BY clause."""
        ...

    def having(self, *q_exprs: Any, **kwargs: Any) -> "OxydeTeamQuery":
        """Add HAVING clause for filtering grouped results."""
        ...

    def values(self, *fields: Literal["created_at", "description", "id", "key", "logo_url", "name", "updated_at"]) -> "OxydeTeamQuery":
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["created_at", "description", "id", "key", "logo_url", "name", "updated_at"], flat: bool = False) -> "OxydeTeamQuery":
        """Return tuples/values instead of models."""
        ...

    # Terminal methods (async, execute query)

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[OxydeTeam]:
        """Execute query and return all results."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> OxydeTeam | None:
        """Execute query and return first result."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> OxydeTeam | None:
        """Execute query and return last result."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count matching objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def update(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **values: Any,
    ) -> int:
        """Update matching objects."""
        ...

    async def increment(
        self,
        field: str,
        by: int | float = 1,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Atomically increment a field value."""
        ...

    async def delete(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Delete matching objects."""
        ...

class OxydeTeamManager(QueryManager[OxydeTeam]):
    """Type-safe Manager for OxydeTeam model."""

    # Query building methods (sync, return Query)

    def query(self) -> OxydeTeamQuery:
        """Return a Query builder for this model."""
        ...

    def filter(
        self,
        *args: Any,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        description: str | None = None,
        description__contains: str | None = None,
        description__icontains: str | None = None,
        description__startswith: str | None = None,
        description__istartswith: str | None = None,
        description__endswith: str | None = None,
        description__iendswith: str | None = None,
        description__iexact: str | None = None,
        description__in: list[str] | None = None,
        description__isnull: bool | None = None,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        key: str | None = None,
        key__contains: str | None = None,
        key__icontains: str | None = None,
        key__startswith: str | None = None,
        key__istartswith: str | None = None,
        key__endswith: str | None = None,
        key__iendswith: str | None = None,
        key__iexact: str | None = None,
        key__in: list[str] | None = None,
        key__isnull: bool | None = None,
        logo_url: str | None = None,
        logo_url__contains: str | None = None,
        logo_url__icontains: str | None = None,
        logo_url__startswith: str | None = None,
        logo_url__istartswith: str | None = None,
        logo_url__endswith: str | None = None,
        logo_url__iendswith: str | None = None,
        logo_url__iexact: str | None = None,
        logo_url__in: list[str] | None = None,
        logo_url__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
    ) -> OxydeTeamQuery:
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        description: str | None = None,
        description__contains: str | None = None,
        description__icontains: str | None = None,
        description__startswith: str | None = None,
        description__istartswith: str | None = None,
        description__endswith: str | None = None,
        description__iendswith: str | None = None,
        description__iexact: str | None = None,
        description__in: list[str] | None = None,
        description__isnull: bool | None = None,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        key: str | None = None,
        key__contains: str | None = None,
        key__icontains: str | None = None,
        key__startswith: str | None = None,
        key__istartswith: str | None = None,
        key__endswith: str | None = None,
        key__iendswith: str | None = None,
        key__iexact: str | None = None,
        key__in: list[str] | None = None,
        key__isnull: bool | None = None,
        logo_url: str | None = None,
        logo_url__contains: str | None = None,
        logo_url__icontains: str | None = None,
        logo_url__startswith: str | None = None,
        logo_url__istartswith: str | None = None,
        logo_url__endswith: str | None = None,
        logo_url__iendswith: str | None = None,
        logo_url__iexact: str | None = None,
        logo_url__in: list[str] | None = None,
        logo_url__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
    ) -> OxydeTeamQuery:
        """Exclude objects matching field lookups."""
        ...

    def values(self, *fields: Literal["created_at", "description", "id", "key", "logo_url", "name", "updated_at"]) -> OxydeTeamQuery:
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["created_at", "description", "id", "key", "logo_url", "name", "updated_at"], flat: bool = False) -> OxydeTeamQuery:
        """Return tuples/values instead of models."""
        ...

    def distinct(self, distinct: bool = True) -> OxydeTeamQuery:
        """Return distinct results."""
        ...

    def join(self, *paths: str) -> OxydeTeamQuery:
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> OxydeTeamQuery:
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> OxydeTeamQuery:
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> OxydeTeamQuery:
        """Add FOR SHARE lock to query."""
        ...

    # Terminal methods (async, execute query)

    async def get(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> OxydeTeam:
        """Get single object matching lookups."""
        ...

    async def get_or_none(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> OxydeTeam | None:
        """Get object or None if not found."""
        ...

    async def get_or_create(
        self,
        *,
        defaults: dict[str, Any] | None = None,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> tuple[OxydeTeam, bool]:
        """Get object or create if not found. Returns (object, created)."""
        ...

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        mode: str = "models",
    ) -> list[OxydeTeam]:
        """Get all objects."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> OxydeTeam | None:
        """Get first object."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> OxydeTeam | None:
        """Get last object."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count all objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def create(
        self,
        *,
        instance: OxydeTeam | None = None,
        client: Any | None = None,
        using: str | None = None,
        created_at: datetime | None = None,
        description: str | None = None,
        id: str | None = None,
        key: str | None = None,
        logo_url: str | None = None,
        name: str | None = None,
        updated_at: datetime | None = None,
    ) -> OxydeTeam:
        """Create new object."""
        ...

    async def bulk_create(
        self,
        objects: list[OxydeTeam],
        *,
        batch_size: int | None = None,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[OxydeTeam]:
        """Bulk create objects."""
        ...

    async def bulk_update(
        self,
        objects: list[OxydeTeam],
        fields: list[str],
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Bulk update objects."""
        ...



class OxydeTeamMemberQuery(Query[OxydeTeamMember]):
    """Type-safe Query for OxydeTeamMember model."""

    # Query building methods (sync, return Query)

    def filter(
        self,
        *args: Any,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        joined_at: datetime | None = None,
        joined_at__gt: datetime | None = None,
        joined_at__gte: datetime | None = None,
        joined_at__lt: datetime | None = None,
        joined_at__lte: datetime | None = None,
        joined_at__between: tuple[datetime, datetime] | None = None,
        joined_at__range: datetime | None = None,
        joined_at__year: int | None = None,
        joined_at__month: int | None = None,
        joined_at__day: int | None = None,
        joined_at__in: list[datetime] | None = None,
        joined_at__isnull: bool | None = None,
        role: <enum 'TeamRole'> | None = None,
        role__in: list[<enum 'TeamRole'>] | None = None,
        role__isnull: bool | None = None,
        team_id: str | None = None,
        team_id__contains: str | None = None,
        team_id__icontains: str | None = None,
        team_id__startswith: str | None = None,
        team_id__istartswith: str | None = None,
        team_id__endswith: str | None = None,
        team_id__iendswith: str | None = None,
        team_id__iexact: str | None = None,
        team_id__in: list[str] | None = None,
        team_id__isnull: bool | None = None,
        user: OxydeUser | None = None,
        user__in: list[OxydeUser] | None = None,
        user__isnull: bool | None = None,
        user_id: str | None = None,
        user_id__contains: str | None = None,
        user_id__icontains: str | None = None,
        user_id__startswith: str | None = None,
        user_id__istartswith: str | None = None,
        user_id__endswith: str | None = None,
        user_id__iendswith: str | None = None,
        user_id__iexact: str | None = None,
        user_id__in: list[str] | None = None,
        user_id__isnull: bool | None = None,
    ) -> "OxydeTeamMemberQuery":
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        joined_at: datetime | None = None,
        joined_at__gt: datetime | None = None,
        joined_at__gte: datetime | None = None,
        joined_at__lt: datetime | None = None,
        joined_at__lte: datetime | None = None,
        joined_at__between: tuple[datetime, datetime] | None = None,
        joined_at__range: datetime | None = None,
        joined_at__year: int | None = None,
        joined_at__month: int | None = None,
        joined_at__day: int | None = None,
        joined_at__in: list[datetime] | None = None,
        joined_at__isnull: bool | None = None,
        role: <enum 'TeamRole'> | None = None,
        role__in: list[<enum 'TeamRole'>] | None = None,
        role__isnull: bool | None = None,
        team_id: str | None = None,
        team_id__contains: str | None = None,
        team_id__icontains: str | None = None,
        team_id__startswith: str | None = None,
        team_id__istartswith: str | None = None,
        team_id__endswith: str | None = None,
        team_id__iendswith: str | None = None,
        team_id__iexact: str | None = None,
        team_id__in: list[str] | None = None,
        team_id__isnull: bool | None = None,
        user: OxydeUser | None = None,
        user__in: list[OxydeUser] | None = None,
        user__isnull: bool | None = None,
        user_id: str | None = None,
        user_id__contains: str | None = None,
        user_id__icontains: str | None = None,
        user_id__startswith: str | None = None,
        user_id__istartswith: str | None = None,
        user_id__endswith: str | None = None,
        user_id__iendswith: str | None = None,
        user_id__iexact: str | None = None,
        user_id__in: list[str] | None = None,
        user_id__isnull: bool | None = None,
    ) -> "OxydeTeamMemberQuery":
        """Exclude objects matching field lookups."""
        ...

    def order_by(self, *fields: Literal["id", "-id", "joined_at", "-joined_at", "role", "-role", "team_id", "-team_id", "user", "-user", "user_id", "-user_id"]) -> "OxydeTeamMemberQuery":
        """Order results by fields."""
        ...

    def limit(self, n: int) -> "OxydeTeamMemberQuery":
        """Limit number of results."""
        ...

    def offset(self, n: int) -> "OxydeTeamMemberQuery":
        """Skip first n results."""
        ...

    def distinct(self, value: bool = True) -> "OxydeTeamMemberQuery":
        """Return distinct results."""
        ...

    def select(self, *fields: Literal["id", "joined_at", "role", "team_id", "user", "user_id"]) -> "OxydeTeamMemberQuery":
        """Select specific fields."""
        ...

    def join(self, *paths: str) -> "OxydeTeamMemberQuery":
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> "OxydeTeamMemberQuery":
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> "OxydeTeamMemberQuery":
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> "OxydeTeamMemberQuery":
        """Add FOR SHARE lock to query."""
        ...

    def annotate(self, **annotations: Any) -> "OxydeTeamMemberQuery":
        """Add computed fields using aggregate functions."""
        ...

    def group_by(self, *fields: Literal["id", "joined_at", "role", "team_id", "user", "user_id"]) -> "OxydeTeamMemberQuery":
        """Add GROUP BY clause."""
        ...

    def having(self, *q_exprs: Any, **kwargs: Any) -> "OxydeTeamMemberQuery":
        """Add HAVING clause for filtering grouped results."""
        ...

    def values(self, *fields: Literal["id", "joined_at", "role", "team_id", "user", "user_id"]) -> "OxydeTeamMemberQuery":
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["id", "joined_at", "role", "team_id", "user", "user_id"], flat: bool = False) -> "OxydeTeamMemberQuery":
        """Return tuples/values instead of models."""
        ...

    # Terminal methods (async, execute query)

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[OxydeTeamMember]:
        """Execute query and return all results."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> OxydeTeamMember | None:
        """Execute query and return first result."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> OxydeTeamMember | None:
        """Execute query and return last result."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count matching objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def update(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **values: Any,
    ) -> int:
        """Update matching objects."""
        ...

    async def increment(
        self,
        field: str,
        by: int | float = 1,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Atomically increment a field value."""
        ...

    async def delete(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Delete matching objects."""
        ...

class OxydeTeamMemberManager(QueryManager[OxydeTeamMember]):
    """Type-safe Manager for OxydeTeamMember model."""

    # Query building methods (sync, return Query)

    def query(self) -> OxydeTeamMemberQuery:
        """Return a Query builder for this model."""
        ...

    def filter(
        self,
        *args: Any,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        joined_at: datetime | None = None,
        joined_at__gt: datetime | None = None,
        joined_at__gte: datetime | None = None,
        joined_at__lt: datetime | None = None,
        joined_at__lte: datetime | None = None,
        joined_at__between: tuple[datetime, datetime] | None = None,
        joined_at__range: datetime | None = None,
        joined_at__year: int | None = None,
        joined_at__month: int | None = None,
        joined_at__day: int | None = None,
        joined_at__in: list[datetime] | None = None,
        joined_at__isnull: bool | None = None,
        role: <enum 'TeamRole'> | None = None,
        role__in: list[<enum 'TeamRole'>] | None = None,
        role__isnull: bool | None = None,
        team_id: str | None = None,
        team_id__contains: str | None = None,
        team_id__icontains: str | None = None,
        team_id__startswith: str | None = None,
        team_id__istartswith: str | None = None,
        team_id__endswith: str | None = None,
        team_id__iendswith: str | None = None,
        team_id__iexact: str | None = None,
        team_id__in: list[str] | None = None,
        team_id__isnull: bool | None = None,
        user: OxydeUser | None = None,
        user__in: list[OxydeUser] | None = None,
        user__isnull: bool | None = None,
        user_id: str | None = None,
        user_id__contains: str | None = None,
        user_id__icontains: str | None = None,
        user_id__startswith: str | None = None,
        user_id__istartswith: str | None = None,
        user_id__endswith: str | None = None,
        user_id__iendswith: str | None = None,
        user_id__iexact: str | None = None,
        user_id__in: list[str] | None = None,
        user_id__isnull: bool | None = None,
    ) -> OxydeTeamMemberQuery:
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        joined_at: datetime | None = None,
        joined_at__gt: datetime | None = None,
        joined_at__gte: datetime | None = None,
        joined_at__lt: datetime | None = None,
        joined_at__lte: datetime | None = None,
        joined_at__between: tuple[datetime, datetime] | None = None,
        joined_at__range: datetime | None = None,
        joined_at__year: int | None = None,
        joined_at__month: int | None = None,
        joined_at__day: int | None = None,
        joined_at__in: list[datetime] | None = None,
        joined_at__isnull: bool | None = None,
        role: <enum 'TeamRole'> | None = None,
        role__in: list[<enum 'TeamRole'>] | None = None,
        role__isnull: bool | None = None,
        team_id: str | None = None,
        team_id__contains: str | None = None,
        team_id__icontains: str | None = None,
        team_id__startswith: str | None = None,
        team_id__istartswith: str | None = None,
        team_id__endswith: str | None = None,
        team_id__iendswith: str | None = None,
        team_id__iexact: str | None = None,
        team_id__in: list[str] | None = None,
        team_id__isnull: bool | None = None,
        user: OxydeUser | None = None,
        user__in: list[OxydeUser] | None = None,
        user__isnull: bool | None = None,
        user_id: str | None = None,
        user_id__contains: str | None = None,
        user_id__icontains: str | None = None,
        user_id__startswith: str | None = None,
        user_id__istartswith: str | None = None,
        user_id__endswith: str | None = None,
        user_id__iendswith: str | None = None,
        user_id__iexact: str | None = None,
        user_id__in: list[str] | None = None,
        user_id__isnull: bool | None = None,
    ) -> OxydeTeamMemberQuery:
        """Exclude objects matching field lookups."""
        ...

    def values(self, *fields: Literal["id", "joined_at", "role", "team_id", "user", "user_id"]) -> OxydeTeamMemberQuery:
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["id", "joined_at", "role", "team_id", "user", "user_id"], flat: bool = False) -> OxydeTeamMemberQuery:
        """Return tuples/values instead of models."""
        ...

    def distinct(self, distinct: bool = True) -> OxydeTeamMemberQuery:
        """Return distinct results."""
        ...

    def join(self, *paths: str) -> OxydeTeamMemberQuery:
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> OxydeTeamMemberQuery:
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> OxydeTeamMemberQuery:
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> OxydeTeamMemberQuery:
        """Add FOR SHARE lock to query."""
        ...

    # Terminal methods (async, execute query)

    async def get(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> OxydeTeamMember:
        """Get single object matching lookups."""
        ...

    async def get_or_none(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> OxydeTeamMember | None:
        """Get object or None if not found."""
        ...

    async def get_or_create(
        self,
        *,
        defaults: dict[str, Any] | None = None,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> tuple[OxydeTeamMember, bool]:
        """Get object or create if not found. Returns (object, created)."""
        ...

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        mode: str = "models",
    ) -> list[OxydeTeamMember]:
        """Get all objects."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> OxydeTeamMember | None:
        """Get first object."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> OxydeTeamMember | None:
        """Get last object."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count all objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def create(
        self,
        *,
        instance: OxydeTeamMember | None = None,
        client: Any | None = None,
        using: str | None = None,
        id: str | None = None,
        joined_at: datetime | None = None,
        role: <enum 'TeamRole'> | None = None,
        team_id: str | None = None,
        user: OxydeUser | None = None,
        user_id: str | None = None,
    ) -> OxydeTeamMember:
        """Create new object."""
        ...

    async def bulk_create(
        self,
        objects: list[OxydeTeamMember],
        *,
        batch_size: int | None = None,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[OxydeTeamMember]:
        """Bulk create objects."""
        ...

    async def bulk_update(
        self,
        objects: list[OxydeTeamMember],
        fields: list[str],
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Bulk update objects."""
        ...



class OxydeTeamInvitationQuery(Query[OxydeTeamInvitation]):
    """Type-safe Query for OxydeTeamInvitation model."""

    # Query building methods (sync, return Query)

    def filter(
        self,
        *args: Any,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        email: str | None = None,
        email__contains: str | None = None,
        email__icontains: str | None = None,
        email__startswith: str | None = None,
        email__istartswith: str | None = None,
        email__endswith: str | None = None,
        email__iendswith: str | None = None,
        email__iexact: str | None = None,
        email__in: list[str] | None = None,
        email__isnull: bool | None = None,
        expires_at: datetime | None = None,
        expires_at__gt: datetime | None = None,
        expires_at__gte: datetime | None = None,
        expires_at__lt: datetime | None = None,
        expires_at__lte: datetime | None = None,
        expires_at__between: tuple[datetime, datetime] | None = None,
        expires_at__range: datetime | None = None,
        expires_at__year: int | None = None,
        expires_at__month: int | None = None,
        expires_at__day: int | None = None,
        expires_at__in: list[datetime] | None = None,
        expires_at__isnull: bool | None = None,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        invited_by: OxydeUser | None = None,
        invited_by__in: list[OxydeUser] | None = None,
        invited_by__isnull: bool | None = None,
        invited_by_id: str | None = None,
        invited_by_id__contains: str | None = None,
        invited_by_id__icontains: str | None = None,
        invited_by_id__startswith: str | None = None,
        invited_by_id__istartswith: str | None = None,
        invited_by_id__endswith: str | None = None,
        invited_by_id__iendswith: str | None = None,
        invited_by_id__iexact: str | None = None,
        invited_by_id__in: list[str] | None = None,
        invited_by_id__isnull: bool | None = None,
        role: <enum 'TeamRole'> | None = None,
        role__in: list[<enum 'TeamRole'>] | None = None,
        role__isnull: bool | None = None,
        status: <enum 'InvitationStatus'> | None = None,
        status__in: list[<enum 'InvitationStatus'>] | None = None,
        status__isnull: bool | None = None,
        team_id: str | None = None,
        team_id__contains: str | None = None,
        team_id__icontains: str | None = None,
        team_id__startswith: str | None = None,
        team_id__istartswith: str | None = None,
        team_id__endswith: str | None = None,
        team_id__iendswith: str | None = None,
        team_id__iexact: str | None = None,
        team_id__in: list[str] | None = None,
        team_id__isnull: bool | None = None,
        token: str | None = None,
        token__contains: str | None = None,
        token__icontains: str | None = None,
        token__startswith: str | None = None,
        token__istartswith: str | None = None,
        token__endswith: str | None = None,
        token__iendswith: str | None = None,
        token__iexact: str | None = None,
        token__in: list[str] | None = None,
        token__isnull: bool | None = None,
    ) -> "OxydeTeamInvitationQuery":
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        email: str | None = None,
        email__contains: str | None = None,
        email__icontains: str | None = None,
        email__startswith: str | None = None,
        email__istartswith: str | None = None,
        email__endswith: str | None = None,
        email__iendswith: str | None = None,
        email__iexact: str | None = None,
        email__in: list[str] | None = None,
        email__isnull: bool | None = None,
        expires_at: datetime | None = None,
        expires_at__gt: datetime | None = None,
        expires_at__gte: datetime | None = None,
        expires_at__lt: datetime | None = None,
        expires_at__lte: datetime | None = None,
        expires_at__between: tuple[datetime, datetime] | None = None,
        expires_at__range: datetime | None = None,
        expires_at__year: int | None = None,
        expires_at__month: int | None = None,
        expires_at__day: int | None = None,
        expires_at__in: list[datetime] | None = None,
        expires_at__isnull: bool | None = None,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        invited_by: OxydeUser | None = None,
        invited_by__in: list[OxydeUser] | None = None,
        invited_by__isnull: bool | None = None,
        invited_by_id: str | None = None,
        invited_by_id__contains: str | None = None,
        invited_by_id__icontains: str | None = None,
        invited_by_id__startswith: str | None = None,
        invited_by_id__istartswith: str | None = None,
        invited_by_id__endswith: str | None = None,
        invited_by_id__iendswith: str | None = None,
        invited_by_id__iexact: str | None = None,
        invited_by_id__in: list[str] | None = None,
        invited_by_id__isnull: bool | None = None,
        role: <enum 'TeamRole'> | None = None,
        role__in: list[<enum 'TeamRole'>] | None = None,
        role__isnull: bool | None = None,
        status: <enum 'InvitationStatus'> | None = None,
        status__in: list[<enum 'InvitationStatus'>] | None = None,
        status__isnull: bool | None = None,
        team_id: str | None = None,
        team_id__contains: str | None = None,
        team_id__icontains: str | None = None,
        team_id__startswith: str | None = None,
        team_id__istartswith: str | None = None,
        team_id__endswith: str | None = None,
        team_id__iendswith: str | None = None,
        team_id__iexact: str | None = None,
        team_id__in: list[str] | None = None,
        team_id__isnull: bool | None = None,
        token: str | None = None,
        token__contains: str | None = None,
        token__icontains: str | None = None,
        token__startswith: str | None = None,
        token__istartswith: str | None = None,
        token__endswith: str | None = None,
        token__iendswith: str | None = None,
        token__iexact: str | None = None,
        token__in: list[str] | None = None,
        token__isnull: bool | None = None,
    ) -> "OxydeTeamInvitationQuery":
        """Exclude objects matching field lookups."""
        ...

    def order_by(self, *fields: Literal["created_at", "-created_at", "email", "-email", "expires_at", "-expires_at", "id", "-id", "invited_by", "-invited_by", "invited_by_id", "-invited_by_id", "role", "-role", "status", "-status", "team_id", "-team_id", "token", "-token"]) -> "OxydeTeamInvitationQuery":
        """Order results by fields."""
        ...

    def limit(self, n: int) -> "OxydeTeamInvitationQuery":
        """Limit number of results."""
        ...

    def offset(self, n: int) -> "OxydeTeamInvitationQuery":
        """Skip first n results."""
        ...

    def distinct(self, value: bool = True) -> "OxydeTeamInvitationQuery":
        """Return distinct results."""
        ...

    def select(self, *fields: Literal["created_at", "email", "expires_at", "id", "invited_by", "invited_by_id", "role", "status", "team_id", "token"]) -> "OxydeTeamInvitationQuery":
        """Select specific fields."""
        ...

    def join(self, *paths: str) -> "OxydeTeamInvitationQuery":
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> "OxydeTeamInvitationQuery":
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> "OxydeTeamInvitationQuery":
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> "OxydeTeamInvitationQuery":
        """Add FOR SHARE lock to query."""
        ...

    def annotate(self, **annotations: Any) -> "OxydeTeamInvitationQuery":
        """Add computed fields using aggregate functions."""
        ...

    def group_by(self, *fields: Literal["created_at", "email", "expires_at", "id", "invited_by", "invited_by_id", "role", "status", "team_id", "token"]) -> "OxydeTeamInvitationQuery":
        """Add GROUP BY clause."""
        ...

    def having(self, *q_exprs: Any, **kwargs: Any) -> "OxydeTeamInvitationQuery":
        """Add HAVING clause for filtering grouped results."""
        ...

    def values(self, *fields: Literal["created_at", "email", "expires_at", "id", "invited_by", "invited_by_id", "role", "status", "team_id", "token"]) -> "OxydeTeamInvitationQuery":
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["created_at", "email", "expires_at", "id", "invited_by", "invited_by_id", "role", "status", "team_id", "token"], flat: bool = False) -> "OxydeTeamInvitationQuery":
        """Return tuples/values instead of models."""
        ...

    # Terminal methods (async, execute query)

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[OxydeTeamInvitation]:
        """Execute query and return all results."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> OxydeTeamInvitation | None:
        """Execute query and return first result."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> OxydeTeamInvitation | None:
        """Execute query and return last result."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count matching objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def update(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **values: Any,
    ) -> int:
        """Update matching objects."""
        ...

    async def increment(
        self,
        field: str,
        by: int | float = 1,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Atomically increment a field value."""
        ...

    async def delete(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Delete matching objects."""
        ...

class OxydeTeamInvitationManager(QueryManager[OxydeTeamInvitation]):
    """Type-safe Manager for OxydeTeamInvitation model."""

    # Query building methods (sync, return Query)

    def query(self) -> OxydeTeamInvitationQuery:
        """Return a Query builder for this model."""
        ...

    def filter(
        self,
        *args: Any,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        email: str | None = None,
        email__contains: str | None = None,
        email__icontains: str | None = None,
        email__startswith: str | None = None,
        email__istartswith: str | None = None,
        email__endswith: str | None = None,
        email__iendswith: str | None = None,
        email__iexact: str | None = None,
        email__in: list[str] | None = None,
        email__isnull: bool | None = None,
        expires_at: datetime | None = None,
        expires_at__gt: datetime | None = None,
        expires_at__gte: datetime | None = None,
        expires_at__lt: datetime | None = None,
        expires_at__lte: datetime | None = None,
        expires_at__between: tuple[datetime, datetime] | None = None,
        expires_at__range: datetime | None = None,
        expires_at__year: int | None = None,
        expires_at__month: int | None = None,
        expires_at__day: int | None = None,
        expires_at__in: list[datetime] | None = None,
        expires_at__isnull: bool | None = None,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        invited_by: OxydeUser | None = None,
        invited_by__in: list[OxydeUser] | None = None,
        invited_by__isnull: bool | None = None,
        invited_by_id: str | None = None,
        invited_by_id__contains: str | None = None,
        invited_by_id__icontains: str | None = None,
        invited_by_id__startswith: str | None = None,
        invited_by_id__istartswith: str | None = None,
        invited_by_id__endswith: str | None = None,
        invited_by_id__iendswith: str | None = None,
        invited_by_id__iexact: str | None = None,
        invited_by_id__in: list[str] | None = None,
        invited_by_id__isnull: bool | None = None,
        role: <enum 'TeamRole'> | None = None,
        role__in: list[<enum 'TeamRole'>] | None = None,
        role__isnull: bool | None = None,
        status: <enum 'InvitationStatus'> | None = None,
        status__in: list[<enum 'InvitationStatus'>] | None = None,
        status__isnull: bool | None = None,
        team_id: str | None = None,
        team_id__contains: str | None = None,
        team_id__icontains: str | None = None,
        team_id__startswith: str | None = None,
        team_id__istartswith: str | None = None,
        team_id__endswith: str | None = None,
        team_id__iendswith: str | None = None,
        team_id__iexact: str | None = None,
        team_id__in: list[str] | None = None,
        team_id__isnull: bool | None = None,
        token: str | None = None,
        token__contains: str | None = None,
        token__icontains: str | None = None,
        token__startswith: str | None = None,
        token__istartswith: str | None = None,
        token__endswith: str | None = None,
        token__iendswith: str | None = None,
        token__iexact: str | None = None,
        token__in: list[str] | None = None,
        token__isnull: bool | None = None,
    ) -> OxydeTeamInvitationQuery:
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        email: str | None = None,
        email__contains: str | None = None,
        email__icontains: str | None = None,
        email__startswith: str | None = None,
        email__istartswith: str | None = None,
        email__endswith: str | None = None,
        email__iendswith: str | None = None,
        email__iexact: str | None = None,
        email__in: list[str] | None = None,
        email__isnull: bool | None = None,
        expires_at: datetime | None = None,
        expires_at__gt: datetime | None = None,
        expires_at__gte: datetime | None = None,
        expires_at__lt: datetime | None = None,
        expires_at__lte: datetime | None = None,
        expires_at__between: tuple[datetime, datetime] | None = None,
        expires_at__range: datetime | None = None,
        expires_at__year: int | None = None,
        expires_at__month: int | None = None,
        expires_at__day: int | None = None,
        expires_at__in: list[datetime] | None = None,
        expires_at__isnull: bool | None = None,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        invited_by: OxydeUser | None = None,
        invited_by__in: list[OxydeUser] | None = None,
        invited_by__isnull: bool | None = None,
        invited_by_id: str | None = None,
        invited_by_id__contains: str | None = None,
        invited_by_id__icontains: str | None = None,
        invited_by_id__startswith: str | None = None,
        invited_by_id__istartswith: str | None = None,
        invited_by_id__endswith: str | None = None,
        invited_by_id__iendswith: str | None = None,
        invited_by_id__iexact: str | None = None,
        invited_by_id__in: list[str] | None = None,
        invited_by_id__isnull: bool | None = None,
        role: <enum 'TeamRole'> | None = None,
        role__in: list[<enum 'TeamRole'>] | None = None,
        role__isnull: bool | None = None,
        status: <enum 'InvitationStatus'> | None = None,
        status__in: list[<enum 'InvitationStatus'>] | None = None,
        status__isnull: bool | None = None,
        team_id: str | None = None,
        team_id__contains: str | None = None,
        team_id__icontains: str | None = None,
        team_id__startswith: str | None = None,
        team_id__istartswith: str | None = None,
        team_id__endswith: str | None = None,
        team_id__iendswith: str | None = None,
        team_id__iexact: str | None = None,
        team_id__in: list[str] | None = None,
        team_id__isnull: bool | None = None,
        token: str | None = None,
        token__contains: str | None = None,
        token__icontains: str | None = None,
        token__startswith: str | None = None,
        token__istartswith: str | None = None,
        token__endswith: str | None = None,
        token__iendswith: str | None = None,
        token__iexact: str | None = None,
        token__in: list[str] | None = None,
        token__isnull: bool | None = None,
    ) -> OxydeTeamInvitationQuery:
        """Exclude objects matching field lookups."""
        ...

    def values(self, *fields: Literal["created_at", "email", "expires_at", "id", "invited_by", "invited_by_id", "role", "status", "team_id", "token"]) -> OxydeTeamInvitationQuery:
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["created_at", "email", "expires_at", "id", "invited_by", "invited_by_id", "role", "status", "team_id", "token"], flat: bool = False) -> OxydeTeamInvitationQuery:
        """Return tuples/values instead of models."""
        ...

    def distinct(self, distinct: bool = True) -> OxydeTeamInvitationQuery:
        """Return distinct results."""
        ...

    def join(self, *paths: str) -> OxydeTeamInvitationQuery:
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> OxydeTeamInvitationQuery:
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> OxydeTeamInvitationQuery:
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> OxydeTeamInvitationQuery:
        """Add FOR SHARE lock to query."""
        ...

    # Terminal methods (async, execute query)

    async def get(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> OxydeTeamInvitation:
        """Get single object matching lookups."""
        ...

    async def get_or_none(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> OxydeTeamInvitation | None:
        """Get object or None if not found."""
        ...

    async def get_or_create(
        self,
        *,
        defaults: dict[str, Any] | None = None,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> tuple[OxydeTeamInvitation, bool]:
        """Get object or create if not found. Returns (object, created)."""
        ...

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        mode: str = "models",
    ) -> list[OxydeTeamInvitation]:
        """Get all objects."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> OxydeTeamInvitation | None:
        """Get first object."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> OxydeTeamInvitation | None:
        """Get last object."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count all objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def create(
        self,
        *,
        instance: OxydeTeamInvitation | None = None,
        client: Any | None = None,
        using: str | None = None,
        created_at: datetime | None = None,
        email: str | None = None,
        expires_at: datetime | None = None,
        id: str | None = None,
        invited_by: OxydeUser | None = None,
        invited_by_id: str | None = None,
        role: <enum 'TeamRole'> | None = None,
        status: <enum 'InvitationStatus'> | None = None,
        team_id: str | None = None,
        token: str | None = None,
    ) -> OxydeTeamInvitation:
        """Create new object."""
        ...

    async def bulk_create(
        self,
        objects: list[OxydeTeamInvitation],
        *,
        batch_size: int | None = None,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[OxydeTeamInvitation]:
        """Bulk create objects."""
        ...

    async def bulk_update(
        self,
        objects: list[OxydeTeamInvitation],
        fields: list[str],
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Bulk update objects."""
        ...
