# Auto-generated by oxyde generate-stubs
# DO NOT EDIT - This file will be overwritten

from typing import Any, Literal
from datetime import datetime, date, time
from decimal import Decimal
from uuid import UUID

from oxyde import OxydeModel
from oxyde.queries import Query, QueryManager


class OxydeUser(OxydeModel):
    class Meta:
        is_table: bool
        table_name: str
    id: str
    email: str
    hashed_password: str
    name: str
    avatar_url: str | None
    is_active: bool
    is_superuser: bool
    created_at: datetime
    updated_at: datetime
    is_agent: bool
    parent_user: OxydeUser | None
    agent_team_id: str | None
    agent_project_id: str | None
    parent_user_id: str | None
    objects: "OxydeUserManager"


class OxydeUserQuery(Query[OxydeUser]):
    """Type-safe Query for OxydeUser model."""

    # Query building methods (sync, return Query)

    def filter(
        self,
        *args: Any,
        agent_project_id: str | None = None,
        agent_project_id__contains: str | None = None,
        agent_project_id__icontains: str | None = None,
        agent_project_id__startswith: str | None = None,
        agent_project_id__istartswith: str | None = None,
        agent_project_id__endswith: str | None = None,
        agent_project_id__iendswith: str | None = None,
        agent_project_id__iexact: str | None = None,
        agent_project_id__in: list[str] | None = None,
        agent_project_id__isnull: bool | None = None,
        agent_team_id: str | None = None,
        agent_team_id__contains: str | None = None,
        agent_team_id__icontains: str | None = None,
        agent_team_id__startswith: str | None = None,
        agent_team_id__istartswith: str | None = None,
        agent_team_id__endswith: str | None = None,
        agent_team_id__iendswith: str | None = None,
        agent_team_id__iexact: str | None = None,
        agent_team_id__in: list[str] | None = None,
        agent_team_id__isnull: bool | None = None,
        avatar_url: str | None = None,
        avatar_url__contains: str | None = None,
        avatar_url__icontains: str | None = None,
        avatar_url__startswith: str | None = None,
        avatar_url__istartswith: str | None = None,
        avatar_url__endswith: str | None = None,
        avatar_url__iendswith: str | None = None,
        avatar_url__iexact: str | None = None,
        avatar_url__in: list[str] | None = None,
        avatar_url__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        email: str | None = None,
        email__contains: str | None = None,
        email__icontains: str | None = None,
        email__startswith: str | None = None,
        email__istartswith: str | None = None,
        email__endswith: str | None = None,
        email__iendswith: str | None = None,
        email__iexact: str | None = None,
        email__in: list[str] | None = None,
        email__isnull: bool | None = None,
        hashed_password: str | None = None,
        hashed_password__contains: str | None = None,
        hashed_password__icontains: str | None = None,
        hashed_password__startswith: str | None = None,
        hashed_password__istartswith: str | None = None,
        hashed_password__endswith: str | None = None,
        hashed_password__iendswith: str | None = None,
        hashed_password__iexact: str | None = None,
        hashed_password__in: list[str] | None = None,
        hashed_password__isnull: bool | None = None,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        is_active: bool | None = None,
        is_active__in: list[bool] | None = None,
        is_active__isnull: bool | None = None,
        is_agent: bool | None = None,
        is_agent__in: list[bool] | None = None,
        is_agent__isnull: bool | None = None,
        is_superuser: bool | None = None,
        is_superuser__in: list[bool] | None = None,
        is_superuser__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        parent_user: OxydeUser | None = None,
        parent_user__in: list[OxydeUser] | None = None,
        parent_user__isnull: bool | None = None,
        parent_user_id: str | None = None,
        parent_user_id__contains: str | None = None,
        parent_user_id__icontains: str | None = None,
        parent_user_id__startswith: str | None = None,
        parent_user_id__istartswith: str | None = None,
        parent_user_id__endswith: str | None = None,
        parent_user_id__iendswith: str | None = None,
        parent_user_id__iexact: str | None = None,
        parent_user_id__in: list[str] | None = None,
        parent_user_id__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
    ) -> "OxydeUserQuery":
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        agent_project_id: str | None = None,
        agent_project_id__contains: str | None = None,
        agent_project_id__icontains: str | None = None,
        agent_project_id__startswith: str | None = None,
        agent_project_id__istartswith: str | None = None,
        agent_project_id__endswith: str | None = None,
        agent_project_id__iendswith: str | None = None,
        agent_project_id__iexact: str | None = None,
        agent_project_id__in: list[str] | None = None,
        agent_project_id__isnull: bool | None = None,
        agent_team_id: str | None = None,
        agent_team_id__contains: str | None = None,
        agent_team_id__icontains: str | None = None,
        agent_team_id__startswith: str | None = None,
        agent_team_id__istartswith: str | None = None,
        agent_team_id__endswith: str | None = None,
        agent_team_id__iendswith: str | None = None,
        agent_team_id__iexact: str | None = None,
        agent_team_id__in: list[str] | None = None,
        agent_team_id__isnull: bool | None = None,
        avatar_url: str | None = None,
        avatar_url__contains: str | None = None,
        avatar_url__icontains: str | None = None,
        avatar_url__startswith: str | None = None,
        avatar_url__istartswith: str | None = None,
        avatar_url__endswith: str | None = None,
        avatar_url__iendswith: str | None = None,
        avatar_url__iexact: str | None = None,
        avatar_url__in: list[str] | None = None,
        avatar_url__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        email: str | None = None,
        email__contains: str | None = None,
        email__icontains: str | None = None,
        email__startswith: str | None = None,
        email__istartswith: str | None = None,
        email__endswith: str | None = None,
        email__iendswith: str | None = None,
        email__iexact: str | None = None,
        email__in: list[str] | None = None,
        email__isnull: bool | None = None,
        hashed_password: str | None = None,
        hashed_password__contains: str | None = None,
        hashed_password__icontains: str | None = None,
        hashed_password__startswith: str | None = None,
        hashed_password__istartswith: str | None = None,
        hashed_password__endswith: str | None = None,
        hashed_password__iendswith: str | None = None,
        hashed_password__iexact: str | None = None,
        hashed_password__in: list[str] | None = None,
        hashed_password__isnull: bool | None = None,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        is_active: bool | None = None,
        is_active__in: list[bool] | None = None,
        is_active__isnull: bool | None = None,
        is_agent: bool | None = None,
        is_agent__in: list[bool] | None = None,
        is_agent__isnull: bool | None = None,
        is_superuser: bool | None = None,
        is_superuser__in: list[bool] | None = None,
        is_superuser__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        parent_user: OxydeUser | None = None,
        parent_user__in: list[OxydeUser] | None = None,
        parent_user__isnull: bool | None = None,
        parent_user_id: str | None = None,
        parent_user_id__contains: str | None = None,
        parent_user_id__icontains: str | None = None,
        parent_user_id__startswith: str | None = None,
        parent_user_id__istartswith: str | None = None,
        parent_user_id__endswith: str | None = None,
        parent_user_id__iendswith: str | None = None,
        parent_user_id__iexact: str | None = None,
        parent_user_id__in: list[str] | None = None,
        parent_user_id__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
    ) -> "OxydeUserQuery":
        """Exclude objects matching field lookups."""
        ...

    def order_by(self, *fields: Literal["agent_project_id", "-agent_project_id", "agent_team_id", "-agent_team_id", "avatar_url", "-avatar_url", "created_at", "-created_at", "email", "-email", "hashed_password", "-hashed_password", "id", "-id", "is_active", "-is_active", "is_agent", "-is_agent", "is_superuser", "-is_superuser", "name", "-name", "parent_user", "-parent_user", "parent_user_id", "-parent_user_id", "updated_at", "-updated_at"]) -> "OxydeUserQuery":
        """Order results by fields."""
        ...

    def limit(self, n: int) -> "OxydeUserQuery":
        """Limit number of results."""
        ...

    def offset(self, n: int) -> "OxydeUserQuery":
        """Skip first n results."""
        ...

    def distinct(self, value: bool = True) -> "OxydeUserQuery":
        """Return distinct results."""
        ...

    def select(self, *fields: Literal["agent_project_id", "agent_team_id", "avatar_url", "created_at", "email", "hashed_password", "id", "is_active", "is_agent", "is_superuser", "name", "parent_user", "parent_user_id", "updated_at"]) -> "OxydeUserQuery":
        """Select specific fields."""
        ...

    def join(self, *paths: str) -> "OxydeUserQuery":
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> "OxydeUserQuery":
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> "OxydeUserQuery":
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> "OxydeUserQuery":
        """Add FOR SHARE lock to query."""
        ...

    def annotate(self, **annotations: Any) -> "OxydeUserQuery":
        """Add computed fields using aggregate functions."""
        ...

    def group_by(self, *fields: Literal["agent_project_id", "agent_team_id", "avatar_url", "created_at", "email", "hashed_password", "id", "is_active", "is_agent", "is_superuser", "name", "parent_user", "parent_user_id", "updated_at"]) -> "OxydeUserQuery":
        """Add GROUP BY clause."""
        ...

    def having(self, *q_exprs: Any, **kwargs: Any) -> "OxydeUserQuery":
        """Add HAVING clause for filtering grouped results."""
        ...

    def values(self, *fields: Literal["agent_project_id", "agent_team_id", "avatar_url", "created_at", "email", "hashed_password", "id", "is_active", "is_agent", "is_superuser", "name", "parent_user", "parent_user_id", "updated_at"]) -> "OxydeUserQuery":
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["agent_project_id", "agent_team_id", "avatar_url", "created_at", "email", "hashed_password", "id", "is_active", "is_agent", "is_superuser", "name", "parent_user", "parent_user_id", "updated_at"], flat: bool = False) -> "OxydeUserQuery":
        """Return tuples/values instead of models."""
        ...

    # Terminal methods (async, execute query)

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[OxydeUser]:
        """Execute query and return all results."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> OxydeUser | None:
        """Execute query and return first result."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> OxydeUser | None:
        """Execute query and return last result."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count matching objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def update(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **values: Any,
    ) -> int:
        """Update matching objects."""
        ...

    async def increment(
        self,
        field: str,
        by: int | float = 1,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Atomically increment a field value."""
        ...

    async def delete(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Delete matching objects."""
        ...

class OxydeUserManager(QueryManager[OxydeUser]):
    """Type-safe Manager for OxydeUser model."""

    # Query building methods (sync, return Query)

    def query(self) -> OxydeUserQuery:
        """Return a Query builder for this model."""
        ...

    def filter(
        self,
        *args: Any,
        agent_project_id: str | None = None,
        agent_project_id__contains: str | None = None,
        agent_project_id__icontains: str | None = None,
        agent_project_id__startswith: str | None = None,
        agent_project_id__istartswith: str | None = None,
        agent_project_id__endswith: str | None = None,
        agent_project_id__iendswith: str | None = None,
        agent_project_id__iexact: str | None = None,
        agent_project_id__in: list[str] | None = None,
        agent_project_id__isnull: bool | None = None,
        agent_team_id: str | None = None,
        agent_team_id__contains: str | None = None,
        agent_team_id__icontains: str | None = None,
        agent_team_id__startswith: str | None = None,
        agent_team_id__istartswith: str | None = None,
        agent_team_id__endswith: str | None = None,
        agent_team_id__iendswith: str | None = None,
        agent_team_id__iexact: str | None = None,
        agent_team_id__in: list[str] | None = None,
        agent_team_id__isnull: bool | None = None,
        avatar_url: str | None = None,
        avatar_url__contains: str | None = None,
        avatar_url__icontains: str | None = None,
        avatar_url__startswith: str | None = None,
        avatar_url__istartswith: str | None = None,
        avatar_url__endswith: str | None = None,
        avatar_url__iendswith: str | None = None,
        avatar_url__iexact: str | None = None,
        avatar_url__in: list[str] | None = None,
        avatar_url__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        email: str | None = None,
        email__contains: str | None = None,
        email__icontains: str | None = None,
        email__startswith: str | None = None,
        email__istartswith: str | None = None,
        email__endswith: str | None = None,
        email__iendswith: str | None = None,
        email__iexact: str | None = None,
        email__in: list[str] | None = None,
        email__isnull: bool | None = None,
        hashed_password: str | None = None,
        hashed_password__contains: str | None = None,
        hashed_password__icontains: str | None = None,
        hashed_password__startswith: str | None = None,
        hashed_password__istartswith: str | None = None,
        hashed_password__endswith: str | None = None,
        hashed_password__iendswith: str | None = None,
        hashed_password__iexact: str | None = None,
        hashed_password__in: list[str] | None = None,
        hashed_password__isnull: bool | None = None,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        is_active: bool | None = None,
        is_active__in: list[bool] | None = None,
        is_active__isnull: bool | None = None,
        is_agent: bool | None = None,
        is_agent__in: list[bool] | None = None,
        is_agent__isnull: bool | None = None,
        is_superuser: bool | None = None,
        is_superuser__in: list[bool] | None = None,
        is_superuser__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        parent_user: OxydeUser | None = None,
        parent_user__in: list[OxydeUser] | None = None,
        parent_user__isnull: bool | None = None,
        parent_user_id: str | None = None,
        parent_user_id__contains: str | None = None,
        parent_user_id__icontains: str | None = None,
        parent_user_id__startswith: str | None = None,
        parent_user_id__istartswith: str | None = None,
        parent_user_id__endswith: str | None = None,
        parent_user_id__iendswith: str | None = None,
        parent_user_id__iexact: str | None = None,
        parent_user_id__in: list[str] | None = None,
        parent_user_id__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
    ) -> OxydeUserQuery:
        """Filter by Q-expressions or field lookups."""
        ...

    def exclude(
        self,
        *args: Any,
        agent_project_id: str | None = None,
        agent_project_id__contains: str | None = None,
        agent_project_id__icontains: str | None = None,
        agent_project_id__startswith: str | None = None,
        agent_project_id__istartswith: str | None = None,
        agent_project_id__endswith: str | None = None,
        agent_project_id__iendswith: str | None = None,
        agent_project_id__iexact: str | None = None,
        agent_project_id__in: list[str] | None = None,
        agent_project_id__isnull: bool | None = None,
        agent_team_id: str | None = None,
        agent_team_id__contains: str | None = None,
        agent_team_id__icontains: str | None = None,
        agent_team_id__startswith: str | None = None,
        agent_team_id__istartswith: str | None = None,
        agent_team_id__endswith: str | None = None,
        agent_team_id__iendswith: str | None = None,
        agent_team_id__iexact: str | None = None,
        agent_team_id__in: list[str] | None = None,
        agent_team_id__isnull: bool | None = None,
        avatar_url: str | None = None,
        avatar_url__contains: str | None = None,
        avatar_url__icontains: str | None = None,
        avatar_url__startswith: str | None = None,
        avatar_url__istartswith: str | None = None,
        avatar_url__endswith: str | None = None,
        avatar_url__iendswith: str | None = None,
        avatar_url__iexact: str | None = None,
        avatar_url__in: list[str] | None = None,
        avatar_url__isnull: bool | None = None,
        created_at: datetime | None = None,
        created_at__gt: datetime | None = None,
        created_at__gte: datetime | None = None,
        created_at__lt: datetime | None = None,
        created_at__lte: datetime | None = None,
        created_at__between: tuple[datetime, datetime] | None = None,
        created_at__range: datetime | None = None,
        created_at__year: int | None = None,
        created_at__month: int | None = None,
        created_at__day: int | None = None,
        created_at__in: list[datetime] | None = None,
        created_at__isnull: bool | None = None,
        email: str | None = None,
        email__contains: str | None = None,
        email__icontains: str | None = None,
        email__startswith: str | None = None,
        email__istartswith: str | None = None,
        email__endswith: str | None = None,
        email__iendswith: str | None = None,
        email__iexact: str | None = None,
        email__in: list[str] | None = None,
        email__isnull: bool | None = None,
        hashed_password: str | None = None,
        hashed_password__contains: str | None = None,
        hashed_password__icontains: str | None = None,
        hashed_password__startswith: str | None = None,
        hashed_password__istartswith: str | None = None,
        hashed_password__endswith: str | None = None,
        hashed_password__iendswith: str | None = None,
        hashed_password__iexact: str | None = None,
        hashed_password__in: list[str] | None = None,
        hashed_password__isnull: bool | None = None,
        id: str | None = None,
        id__contains: str | None = None,
        id__icontains: str | None = None,
        id__startswith: str | None = None,
        id__istartswith: str | None = None,
        id__endswith: str | None = None,
        id__iendswith: str | None = None,
        id__iexact: str | None = None,
        id__in: list[str] | None = None,
        id__isnull: bool | None = None,
        is_active: bool | None = None,
        is_active__in: list[bool] | None = None,
        is_active__isnull: bool | None = None,
        is_agent: bool | None = None,
        is_agent__in: list[bool] | None = None,
        is_agent__isnull: bool | None = None,
        is_superuser: bool | None = None,
        is_superuser__in: list[bool] | None = None,
        is_superuser__isnull: bool | None = None,
        name: str | None = None,
        name__contains: str | None = None,
        name__icontains: str | None = None,
        name__startswith: str | None = None,
        name__istartswith: str | None = None,
        name__endswith: str | None = None,
        name__iendswith: str | None = None,
        name__iexact: str | None = None,
        name__in: list[str] | None = None,
        name__isnull: bool | None = None,
        parent_user: OxydeUser | None = None,
        parent_user__in: list[OxydeUser] | None = None,
        parent_user__isnull: bool | None = None,
        parent_user_id: str | None = None,
        parent_user_id__contains: str | None = None,
        parent_user_id__icontains: str | None = None,
        parent_user_id__startswith: str | None = None,
        parent_user_id__istartswith: str | None = None,
        parent_user_id__endswith: str | None = None,
        parent_user_id__iendswith: str | None = None,
        parent_user_id__iexact: str | None = None,
        parent_user_id__in: list[str] | None = None,
        parent_user_id__isnull: bool | None = None,
        updated_at: datetime | None = None,
        updated_at__gt: datetime | None = None,
        updated_at__gte: datetime | None = None,
        updated_at__lt: datetime | None = None,
        updated_at__lte: datetime | None = None,
        updated_at__between: tuple[datetime, datetime] | None = None,
        updated_at__range: datetime | None = None,
        updated_at__year: int | None = None,
        updated_at__month: int | None = None,
        updated_at__day: int | None = None,
        updated_at__in: list[datetime] | None = None,
        updated_at__isnull: bool | None = None,
    ) -> OxydeUserQuery:
        """Exclude objects matching field lookups."""
        ...

    def values(self, *fields: Literal["agent_project_id", "agent_team_id", "avatar_url", "created_at", "email", "hashed_password", "id", "is_active", "is_agent", "is_superuser", "name", "parent_user", "parent_user_id", "updated_at"]) -> OxydeUserQuery:
        """Return dicts instead of models."""
        ...

    def values_list(self, *fields: Literal["agent_project_id", "agent_team_id", "avatar_url", "created_at", "email", "hashed_password", "id", "is_active", "is_agent", "is_superuser", "name", "parent_user", "parent_user_id", "updated_at"], flat: bool = False) -> OxydeUserQuery:
        """Return tuples/values instead of models."""
        ...

    def distinct(self, distinct: bool = True) -> OxydeUserQuery:
        """Return distinct results."""
        ...

    def join(self, *paths: str) -> OxydeUserQuery:
        """Perform LEFT JOIN for relations."""
        ...

    def prefetch(self, *paths: str) -> OxydeUserQuery:
        """Prefetch related objects (separate queries)."""
        ...

    def for_update(self) -> OxydeUserQuery:
        """Add FOR UPDATE lock to query."""
        ...

    def for_share(self) -> OxydeUserQuery:
        """Add FOR SHARE lock to query."""
        ...

    # Terminal methods (async, execute query)

    async def get(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> OxydeUser:
        """Get single object matching lookups."""
        ...

    async def get_or_none(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> OxydeUser | None:
        """Get object or None if not found."""
        ...

    async def get_or_create(
        self,
        *,
        defaults: dict[str, Any] | None = None,
        client: Any | None = None,
        using: str | None = None,
        **filters: Any,
    ) -> tuple[OxydeUser, bool]:
        """Get object or create if not found. Returns (object, created)."""
        ...

    async def all(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
        mode: str = "models",
    ) -> list[OxydeUser]:
        """Get all objects."""
        ...

    async def first(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> OxydeUser | None:
        """Get first object."""
        ...

    async def last(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> OxydeUser | None:
        """Get last object."""
        ...

    async def count(
        self,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Count all objects."""
        ...

    async def sum(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate sum of field values."""
        ...

    async def avg(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Calculate average of field values."""
        ...

    async def max(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get maximum field value."""
        ...

    async def min(
        self,
        field: str,
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> Any:
        """Get minimum field value."""
        ...

    async def create(
        self,
        *,
        instance: OxydeUser | None = None,
        client: Any | None = None,
        using: str | None = None,
        agent_project_id: str | None = None,
        agent_team_id: str | None = None,
        avatar_url: str | None = None,
        created_at: datetime | None = None,
        email: str | None = None,
        hashed_password: str | None = None,
        id: str | None = None,
        is_active: bool | None = None,
        is_agent: bool | None = None,
        is_superuser: bool | None = None,
        name: str | None = None,
        parent_user: OxydeUser | None = None,
        parent_user_id: str | None = None,
        updated_at: datetime | None = None,
    ) -> OxydeUser:
        """Create new object."""
        ...

    async def bulk_create(
        self,
        objects: list[OxydeUser],
        *,
        batch_size: int | None = None,
        client: Any | None = None,
        using: str | None = None,
    ) -> list[OxydeUser]:
        """Bulk create objects."""
        ...

    async def bulk_update(
        self,
        objects: list[OxydeUser],
        fields: list[str],
        *,
        client: Any | None = None,
        using: str | None = None,
    ) -> int:
        """Bulk update objects."""
        ...
