"""add_epic_to_issuetype_enum

Revision ID: 2975578430bf
Revises: b3b5f41af622
Create Date: 2026-02-13 20:16:14.299749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2975578430bf'
down_revision: Union[str, Sequence[str], None] = 'b3b5f41af622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    No-op for SQLite: enum values are stored as VARCHAR strings,
    so adding EPIC to the Python IssueType enum requires no DDL.
    This migration exists as a version marker.
    """
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
