#!/usr/bin/env python3
"""Regenerate the MCP tool table in cli/README.md from the live toolset.

The table's rows come from ``chaotic_mcp_tools.tools.ALL_TOOLS`` (the same
registry walk that produces docs/mcp-toolset-schema.json), grouped by
name prefix in registration order; the "Equivalent to" column is the one
hand-written thing here, kept in CLI_EQUIVALENTS below so adding a tool
means adding one entry and rerunning this, and forgetting the entry fails
the generator by name (CHT-1395). Before this the README carried a
hand-edited table and a literal count that rotted (CHT-1378).

    cd cli && uv run python scripts/gen_mcp_tool_table.py --write

writes the block between the START/END markers in cli/README.md;
without --write it prints the block. cli/tests/test_mcp_toolset_sync.py
fails when the README block differs from what this renders.
"""
from __future__ import annotations

import sys
from pathlib import Path

from chaotic_mcp_tools.expected import GROUP_ORDER, group_of
from chaotic_mcp_tools.tools import ALL_TOOLS

README = Path(__file__).resolve().parents[1] / "README.md"
SCRIPT = "cli/scripts/gen_mcp_tool_table.py"
REGENERATE = "cd cli && uv run python scripts/gen_mcp_tool_table.py --write"
START = "<!-- mcp-tool-table: generated by scripts/gen_mcp_tool_table.py, do not edit by hand -->"
END = "<!-- /mcp-tool-table -->"

# Tool name -> the CLI command(s) it corresponds to. One line per tool; a
# tool missing here, or an entry naming no tool, is an error.
CLI_EQUIVALENTS: dict[str, str] = {
    "issue_list": "`issue list` (with `all_projects` for team-wide)",
    "issue_view": "`issue show`",
    "issue_create": "`issue create`",
    "issue_update": (
        "`issue update` + `issue assign` (status/priority/estimate/assignee/title/description; "
        "`assignee: \"unassigned\"` clears; `attest` map for ritual notes)"
    ),
    "issue_comment": "`issue comment`",
    "issue_start": "`issue start`",
    "issue_ready": "`issue ready`",
    "issue_relations": "`issue relations`",
    "issue_block": "`issue block`",
    "issue_unblock": "`issue unblock`",
    "issue_label": "`issue update --label` / `--remove-label`",
    "issue_revisions": "`issue history`",
    "issue_revision": "`issue history` (one version)",
    "doc_list": "`doc list`",
    "doc_view": "`doc show`",
    "doc_create": "`doc create`",
    "doc_update": "`doc update`",
    "doc_link": "`doc link`",
    "doc_unlink": "`doc unlink`",
    "doc_revisions": "`doc history`",
    "doc_revision": "`doc history` (one version)",
    "sprint_current": "`sprint current`",
    "sprint_list": "`sprint list`",
    "sprint_close": "`sprint close`",
    "sprint_transactions": "`sprint transactions`",
    "sprint_add": "`sprint add`",
    "sprint_remove": "`sprint remove`",
    "ritual_pending": "`ritual pending`",
    "ritual_list": "`ritual list`",
    "ritual_attest": "`ritual attest`",
    "ritual_complete": "`ritual complete`",
    "inbox_list": "`inbox list`",
    "inbox_mark_read": "`inbox mark-read`",
    "inbox_mark_all_read": "`inbox mark-all-read`",
    "label_list": "`label list`",
    "activity_recent": "`activity`",
    "project_list": "`project list`",
}

class ToolTableError(ValueError):
    """The table cannot be rendered from the current toolset; the message
    names what to edit."""


def render_table(tools=ALL_TOOLS, equivalents: dict[str, str] = CLI_EQUIVALENTS) -> str:
    """The markdown block between the markers, markers included."""
    names = [t.__name__ for t in tools]
    missing = [n for n in names if n not in equivalents]
    unknown = sorted(set(equivalents) - set(names))
    if missing or unknown:
        raise ToolTableError(
            f"CLI_EQUIVALENTS in {SCRIPT} is out of step with ALL_TOOLS: no entry for {missing}; "
            f"entries for unknown tools {unknown}. Fix the dict, then `{REGENERATE}`."
        )
    groups: dict[str, list[str]] = {g: [] for g in GROUP_ORDER}
    for name in names:
        groups[group_of(name)].append(name)
    lines = [START, "", "| Tool | Equivalent to |", "|---|---|"]
    for group in GROUP_ORDER:
        for name in groups[group]:
            lines.append(f"| `{name}` | {equivalents[name]} |")
    lines += ["", END]
    return "\n".join(lines)


def splice(text: str, block: str) -> str:
    """`text` with the one marked block replaced by `block`."""
    if text.count(START) != 1 or text.count(END) != 1 or text.index(START) > text.index(END):
        raise ToolTableError(
            f"{README} must contain exactly one `{START}` followed by one `{END}`"
        )
    start = text.index(START)
    end = text.index(END, start) + len(END)
    return text[:start] + block + text[end:]


def main(argv: list[str]) -> None:
    try:
        block = render_table()
        if "--write" in argv:
            README.write_text(splice(README.read_text(encoding="utf-8"), block), encoding="utf-8")
            print(f"wrote {README}", file=sys.stderr)
        else:
            print(block)
    except ToolTableError as exc:
        sys.exit(str(exc))


if __name__ == "__main__":
    main(sys.argv[1:])
